### ISSUE TITLE
Support for Heroku Provider to Deploy Specific Branches

### ISSUE THREAD

**Issue by loganknecht** [travis-ci/dpl#1001]
Hi there. I hope this is an ok place to request this.

I've been looking through the documentation and I don't see any support for this. If I'm misunderstanding the `dpl` tool and/or it's usage I would really appreciate any correction on how to achieve what I'm trying to do.

# Goal

I want to be able to use the `dpl` tool to deploy specified branches in my ci/cd.

# Current Steps

- Install heroku CLI
    - `curl https://cli-assets.heroku.com/install-ubuntu.sh | sh`
- Installs deploy tool for heroku
    - `apt-get update -qy`
    - `apt-get install -y ruby-dev`
    - `gem install dpl`
    - `dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY`

This works. However, if my understanding is correct this is only doing a deploy of my `master` branch.

# Points of Confusion

I'm reading the [docs here for deploying specific branches](https://docs.travis-ci.com/user/deployment/heroku/#deploying-specific-branches). I see that there is indeed an option to specify a branch. However this looks like it only works when using a `.travis.yml` file.

# Request

Please make it so the `dpl` command supports the ability to target a specific branch for the `Heroku` provider.

Perhaps the command might look like this
`dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --on=$GIT_BRANCH_NAME`

**Comment by svenfuchs** [comment]
@loganknecht thanks for the request, especially a this well written one :)

if you don't have a `.travis.yml` file, can i ask what CI/CD context you are using `dpl` on? 

as for your request, the condition mentioned in our documentation is a Bash condition, i.e. our build script compiler would wrap it into a Bash `if` statement, so I think `dpl` is not the right place to accept that condition. i'm going to defer to @BanzaiMan's opinion though.

in any case, in the meantime you can achieve the same thing by doing something like:

```
[[ $(git rev-parse --abbrev-ref HEAD) = master ]] && dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
```

**Comment by loganknecht** [comment]
@svenfuchs Thank you for such a quick reply!

The CI/CD solution I'm using is GitLab.

The reference I'm using is [this page] (https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html).

The issue is that I'm definitely going to want to push my master branch for full deployments, but if I want to test in a staging environment before I merge to a develop I can't.

I will add tithe `.gitlab-ci.yaml` comments when I have access to them later, but they're very simple.

If I try to use the Heroku cli tool, I use the environment variable `$HEROKU_API_KEY` for authentication, but instead it will prohibit me from doing so when I run the `git push $DESIRED_BRANCH:$TARGET_BRANCH` because the authentication between git and the heroku cli are two different mechanisms.

As a result the Gitlab suggested solution is to use the above link, which shows the usage of the `dpl`command, but that locks me into just targeting master branch destinations for deploy.

I will try your suggestion later, but I'm not sure if that will achieve my goal.

**Comment by svenfuchs** [comment]
@loganknecht thanks for the extra details. 

i am not super familiar with GitLab's build configuration format, but it is my understanding that you can use GitLab's config format features to include/exclude things to only run on specific branches. Maybe this helps: https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-advanced

also, again, since your `dpl` command is just a Bash command, you can most certainly use a Bash condition like so:

```
[[ $(git rev-parse --abbrev-ref HEAD) = master ]] && dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
```

if none of this works then maybe it might be best to also turn to GitLab's support. your usecase seems like a very standard usecase, and i am sure they can point you in the right direction.

**Comment by loganknecht** [comment]
@svenfuchs I apologize ahead of time if I'm misunderstanding some of this.

The Gitlab feature to include/exclude is useful for determining a job to run. In my case, I want the job to run on every merge request. This job would deploy that branch to a specific heroku app.

Please see my gitlab configuration:
```
# CI Variables from GitLab
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
api-deploy:
  stage: deploy
  variables:
    HEROKU_APP_NAME: "example-name"
    HEROKU_API_KEY: "65a7e475-3d8a-41a3-952c-c82518f4c872"
  image: python:3.7
  script:
    # Assumes you start in `/builds/project-0/`
    # Install heroku CLI
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    # Installs deploy tool for heroku
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --on=$DESIRED_BRANCH_TO_DEPLOY
```

I first tried using just the `heroku cli` and `git`, but the authentication bit was what I got snagged on. 

Then I used the `dpl` command like the guide demonstrated, however the `dpl` tool appears to pull only from the `master` branch when you use it. 

Because it is targeting the `master` branch, but in my ci/cd deployment I want to use the `feature` branch, I have no way to control what branch gets deployed when using this command:
`dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY`

Every time `dpl` targets the `master` branch for deployment. This means if I want to test the `feature` branch changes in my heroku instance before my changes are merged into master I would have to merge the code into master to deploy it to heroku. And that would defeat the purpose of that effort.

The bash you suggested, does the same operation. Which would be fine, except it also does not allow me the ability to select which branch is deployed on the specified heroku instance.

Am I misunderstanding how to choose what gets deployed to `heroku` using the `dpl` tool?
