### ISSUE TITLE
Windows + PyPI is still broken.

### ISSUE THREAD

**Issue by brandtbucher** [travis-ci/dpl#1009]
Original issue #955 was closed by a bot, but the issue still hasn't been fixed! Repeated here:

- - -

I've recently tried deployment using Travis and Windows. The error I get when installing deployment requirements:

```
$ ruby -S gem install dpl
Successfully installed dpl-pypi-1.10.7
Parsing documentation for dpl-pypi-1.10.7
Installing ri documentation for dpl-pypi-1.10.7
Done installing documentation for dpl-pypi after 0 seconds
1 gem installed
Installing deploy dependencies
failed to deploy
-z was unexpected at this time.
Couldn't install pip, setuptools, twine or wheel.
```

It seems like it tries to use `cmd` instead of `bash`. I've dig into the source code and found [this](https://github.com/travis-ci/dpl/blob/844acf450f57ec26bb2117c83fcf89504dd4964d/lib/dpl/provider/pypi.rb#L70) so I think that `-z` comes from this line. I don't know if it is enough to just prefix this command with `bash -c`. What I am afraid of here is that Windows uses git bash for its build scripts and `cmd` is used here so I am not sure whether virtual environment would be even preserved here.

**Comment by pfaion** [comment]
If someone comes across this:

You can do a manual deploy via a script instead. This is what worked for my use case, not everything might be necessary for a minimal setup though! You might want to fine-tune the script for your use case.

file **.travis.yml**:
```yml
os: windows
language: sh

install: choco install python --version 3.6.8
env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
script: python --version

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./.travis/deploy.sh
```

file **.travis/deploy.sh**:
```bash
pip install twine wheel
python ./setup.py sdist bdist_wheel
twine upload \
    --username "************" \
    --password "************" \
    ./dist/*
```

Installing python3 takes quite some time, but I couldn't get it to work out of the box with the pre-installed python2 and I needed a python 3.6 wheel anyways.
