### ISSUE TITLE
Github Pages deployment is broken with dpl-pages-1.10.12

### ISSUE THREAD

**Issue by jmetzz** [travis-ci/dpl#1071]
There are already a few related issues #1026, #9312, #777  and #766 
However, with older versions of dpl-pages.

Snippet of the log:

```
Deploying application
/home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-pages-1.10.12/lib/dpl/provider/pages.rb:141:in `mkdir': File exists @ dir_s_mkdir - /tmp/d20190819-9856-k0udda/work (Errno::EEXIST)
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-pages-1.10.12/lib/dpl/provider/pages.rb:141:in `github_pull_or_init'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-pages-1.10.12/lib/dpl/provider/pages.rb:195:in `block in push_app'
	from /home/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-pages-1.10.12/lib/dpl/provider/pages.rb:190:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.12/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
failed to deploy
```

To see to full build log click at https://travis-ci.org/jmetzz/jmetzz.github.io/builds/573780504

The deploy configuration:

```yml
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
```

**Comment by jmetzz** [comment]
I've solved the issue by specifying the target branch in deploy session:

```yml
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  verbose: true
  on:
    branch: master
```

The error message is still cryptic, though. Should be more clear about the issue.
