### ISSUE TITLE
[Github Releases] Multiple releases generation instead of one (v2.0.0.alpha.5)

### ISSUE THREAD

**Issue by ivangabriele** [travis-ci/dpl#1102]
When I try to use the edge version in order to use the new `release_notes_file` option, it looks like the deployment is trying to create multiple releases instead of just one as you can see:

![Screenshot](https://i.imgur.com/oAT6sCV.png)

I have a feeling there is some loop happening when I look at [Travis output](https://travis-ci.com/ivangabriele/mattermost-uno/jobs/235558862#L257):

1. it creates a first release with the releases notes tagged with the current version,
2. it creates a new release with the releases notes, which generates a draft since there is a tag conflict,
3. it creates another new release with the releases notes **and** the artifact this time, which generates another draft...

Here is my [config](https://github.com/ivangabriele/mattermost-uno/blob/prepare-ci-automated-release/.travis.yml):

```yaml
    - stage: Deploy
      name: Unsigned Extension
      script: skip
      before_deploy:
        - yarn build:release
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key:
          secure: ...
        edge: true
        file: ./mattermost-uno-unsigned.zip
        release_notes_file: ./RELEASE_NOTES.md
        on:
          repo: ivangabriele/mattermost-uno
          tags: true
```

**Comment by svenfuchs** [comment]
@ivangabriele Thanks a lot for the thorough bug report!

This is still a little confusing, but I believe it had something to do with how we evaluated the URL to POST to. I have pushed what I believe is a fix (memoized that method). 

This build https://travis-ci.com/travis-ci/dpl/jobs/235575363 (with this config https://travis-ci.com/travis-ci/dpl/jobs/235575363/config) has just created a single release https://github.com/travis-ci/dpl_test/releases. As you can see it has the `**release notes**` from the file.

I haven't released this, yet. You can test it using:

```yaml
deploy:
- provider: releases
  edge:
    branch: master
```
