### ISSUE TITLE
question/bug(pages): commit_message option doesn't work for GitHub Pages provider

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/dpl#1123]
### 1. Summary

I don't understand, how I can make custom commit message for GitHub Pages provider.

Currently, it's probably impossible.

### 2. MCVE

See [**`KiraCustomDeployMessage` branch**](https://github.com/Kristinita/SashaTravis/tree/KiraCustomDeployMessage) of my demo repository.

+ [**`.travis.yml`**](https://travis-ci.org/Kristinita/SashaTravis/jobs/599035253/config):

```yaml
git:
  depth: 1
language: python
script:
- echo "Kira Goddess!"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $TOKEN_GITHUB_TRAVIS_DEPLOY_DEBUGGING
  keep-history: true
  on:
    branch: KiraCustomDeployMessage
  verbose: true
  local-dir: KiraDir
  commit_message: "KiraGoddess"
env:
  global:
    # [INFO] Encrypted value of $TOKEN_GITHUB_TRAVIS_DEPLOY_DEBUGGING — my active GitHub token
    secure: Wbd/xIWT+HjQl+3cNEtMs8+6Y0Ov/ambNwLqDFwgs4avNoCo3Yfdv96kVs4RRNOyJwBkkAp+UccCbt8xL+vbNacFi/wMXZP+6//+Clz8aJ/wKB4k2HhVIMK6SjYsBWr+/2Ri+Y4yozjT1dUKFhcqL1Xhg/CSEKSAL3EHg30EBndbzK2ejXLffQgCknX5Lg+rsJQ/StlvpqOb1aw1IBx9ZfPwtYMdlJCNqPvMdG1jZiJf9YIs+mOqzY9Jp3PYr0b6X/2KgHIaBN81ksndwcOfauXnD6GXsTlizy0x/hgsCfyoRq4yHgMUPuNYgUjROXRdeBsRH34mVWyD0hqE3sFEnzxdIV1ai1iod0kNYf/75wACdNyis8E8D7M2UHma89kGbXyJSOAOuG5Vk8dbmlsc/2C6JiRfQK2cFTI6HIpFZ4WBBDaqV4txnwKZKwhcH7nGodsNMyVliIQt6/07Yk7x2TdZsUlWDCMQgQX4Lg9FU2MwtRdrdX1CToHq7Yfnp6FZFsPmGNMHzsbsTkqb4CMWXHR1RwRdzUP4QUJ+Hi+dmb/FxoAxKweerDft1+XoBZWBqlAiVpLD1j6HCbVwEc0JwcsrScIo5OHoFQlDG4LScKeJ3J/fCH0IQr1B2/9aeAUVhtUiYZtl4f4FnELLAFGww8h6ojLPV00+Nelpw1KWnFQ=

```

### 3. Expected behavior

Custom deploy message `KiraGoddess`. For real projects, message, that I described [**here**](https://github.com/travis-ci/dpl/issues/913#issuecomment-372577006):

![Expected deploy message](https://camo.githubusercontent.com/d222ae899f52dfa08b82b237e6f4ba028c84c957/68747470733a2f2f692e696d6775722e636f6d2f596667536535572e706e67)

### 4. Actual behavior

1. [**Deploying job log**](https://travis-ci.org/Kristinita/SashaTravis/jobs/599035253#L184-L223)
1. [**Default deploy message**](https://github.com/Kristinita/SashaTravis/commit/dc9281fc5c9def13ebb1f6d9e60c0fa714a517d2):

    ![Default deploy message](https://i.imgur.com/jRfv1DL.png)

### 5. Not helped

1. I tried values of `commit_message` with single, double quotes and without them.
1. Currently, `commit_message` [**not documented**](https://github.com/travis-ci/docs-travis-ci-com/issues/2493), and I was oriented by the [**merged pull request**](https://github.com/travis-ci/dpl/pull/1035/files#diff-e49332845e8ad218044e2347e34f56acR22).
1. [**I couldn't find**](https://github.com/search?p=1&q=commit_message%3A+filename%3A.travis.yml&type=Code) `deploy:commit_message` in `.travis.yml` files of public GitHub repositories.

Thanks.

**Comment by svenfuchs** [comment]
hi @Kristinita, thanks for the super thorough bug report.

this issue has been fixed in `v2` which is currently in beta, and needs an opt-in. you are using the currently still default version `v1`.

this build https://travis-ci.com/travis-ci/dpl/builds/132323465#L193 has pushed https://github.com/travis-ci/dpl_test/commit/c5de42b7be8e824ce7a22f78ef97c54a2ff993e8, using a custom commit message.

this config should make Travis CI use `v2`. the options `skip_cleanup` and `keep_history` now default to `true`, so you can omit them:

```yaml
deploy:
  provider: pages
  edge: true
  github-token: $TOKEN_GITHUB_TRAVIS_DEPLOY_DEBUGGING
  on:
    branch: KiraCustomDeployMessage
  verbose: true
  local_dir: KiraDir
  commit_message: "KiraGoddess"
```

this option `commit_message` is documented on the `v2` page for the `pages` provider: https://docs.travis-ci.com/user/deployment-v2/providers/pages/#known-options

i am going to close this here, assuming that this will resolve the issue for you. please feel free to reopen it if needed.
