### ISSUE TITLE
dpl v2 npm - Provide Auth Token

### ISSUE THREAD

**Issue by boldtrn** [travis-ci/dpl#1129]
I just tried to set up a travis build with dpl v2 for npm. I set my auth_token as encrypted environment variable in the .travis repo as `NPM_API_TOKEN`. When I execute the build, I am shown an error: 

`Missing required option: api_token` 

My .travis.yml looks like this:
```
deploy:
  provider: npm
  edge: true # opt in to dpl v2  
  on:
    tags: true # only deploy when tags are given  
```

So I have not specified the api_token there again. Probably I have to? But how would I reference the environment variable in the .travis.yml?

**Comment by boldtrn** [comment]
I couldn't get v2 to work. Anyway, here is my .travis.yml if anyone is having a similar issue:

```
deploy:
  provider: npm
  email: $NPM_EMAIL
  api-key: $NPM_AUTH_TOKEN
  on:
    tags: true # only deploy when tags are given   
```
