### ISSUE TITLE
Deploy to cloudfoundry seemingly not being triggered

### ISSUE THREAD

**Issue by palfvin** [travis-ci/dpl#115]
We would like to auto-deploy our application to Cloud Foundry. We can deploy from the command line using `dpl`, but after adding a `deploy` section to our .travis.yml, there is no evidence that travis is attempting a deploy.

We are not sure where the failure is happening since we are not seeing any output in the log files. We interacted with @svenfuchs at support@travis-ci.com about this and he suggested we submit an issue here.

Here is the contents of our .travis.yml file, followed by links to our github repository and the associated travis project:

```
language: ruby
script:
- bundle exec rake
- bundle exec rake jasmine:ci
rvm:
- 2.1.0
deploy:
  provider: cloudfoundry
  username:
    secure: HX60jYjZyrKIu7eM4wbzgQuhj22kaH7ZwQ9AcnTTA+eNy+QS86UFmbggJoPgzLNSqiYP+LMOPEGuiCytNOCtNzDx5vaJdqAI5LuXJ2dzgZAHi8Kxc0STp0vYPZludNOPzt3RIWTIqPIIh3wmryAdfdShf3ikQZ99fk6wJ6sE/aI=
  password:
    secure: HOA+R04u3qsKMo7TPRgqfHHQM6bZ1cZklGaIDH+AAWbbXZSCfzUMPt9Ay7sTHfsV3BKFpQ7A6h8rlvrStVcuaomFrIxtSsjD0HQolrpwyeWqSN3O8tq3VjOSxqws+36rGyzA7dCQHxv3oW+QcTZeH+LA8Nr3DaAVARNKpuLM6kc=
  organization: LA-Ping-Pong-Ding-Dongs
  target: api.run.pivotal.io
  space: staging
  edge: true
```

https://github.com/LA-Ping-Pong-Ding-Dongs/pivot-pong/blob/travis_deploy/.travis.yml
https://travis-ci.org/LA-Ping-Pong-Ding-Dongs/pivot-pong

/cc @marianaIam
