### ISSUE TITLE
Invalid option "--token="

### ISSUE THREAD

**Issue by myin142** [travis-ci/dpl#1158]
When I try to deploy my code to github pages, but when trying to deploy it gives me the error `invalid option "--token="`
I have no idea why it shows token. I at least expected `"--github_token="` since I use "github_token" and not "token". So I have no idea how to solve the problem. Found nothing about "token" on the internet.

My deploy section in travis.yml:
```yml
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: "dist/japanese-grammar"
  repo: "myin142/myin142.github.io"
  on:
    branch: travis
```

[Travis Build](https://travis-ci.com/myin142/japanese-grammar/builds/146880019)
