### ISSUE TITLE
glob not working for S3 deployment

### ISSUE THREAD

**Issue by yogingale** [travis-ci/dpl#1187]
I'm trying to deploy on S3 bucket using glob as referenced in https://docs.travis-ci.com/user/deployment/s3/#deploy-one-or-more-files-matching-a-pattern

Travis file - 
```
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true
  glob: static/*
```
But Travis is deploying all the files on S3. Isn't it should only deploy the files from `static/` directory? (https://travis-ci.com/github/yogingale/compilers.live-aws/builds/161296758)

glob was added in - https://github.com/travis-ci/dpl/pull/1153
