### ISSUE TITLE
Chef Supermarket: Parsing of cookbook name fails

### ISSUE THREAD

**Issue by bastianschwarz** [travis-ci/dpl#1199]
Hey there,

it seems I ran into an issue today when trying to deploy a cookbook to the Chef Supermarket:

https://travis-ci.com/github/codenamephp/chef.cookbook.bash/builds/172321001#L1322
```
Uploading cookbook ~> 9.1 to https://supermarket.chef.io/api/v1/cookbooks
Generating metadata for codenamephp_bash from /tmp/chef-codenamephp_bash-build20200620-10387-yttdgq/codenamephp_bash/metadata.rb
$ tar -czf /tmp/~> 9.1.tgz -C /tmp/chef-codenamephp_bash-build20200620-10387-yttdgq .
$ tar -tvf /tmp/~> 9.1.tgz
No such file or directory @ rb_sysopen - /tmp/~> 9.1.tgz (Errno::ENOENT)
failed to deploy
```

The ~> 9.1 just seems to be the last token from the metadata.rb:

https://github.com/codenamephp/chef.cookbook.bash/blob/bd37ebfd565f9e20b5c74c1abff0a346f69777a2/metadata.rb#L13
```
 
# frozen_string_literal: true

name 'codenamephp_bash'
...
issues_url 'https://github.com/codenamephp/chef.cookbook.bash/issues'
source_url 'https://github.com/codenamephp/chef.cookbook.bash'

supports 'debian', '~>9.1'
```
I tried the deployment with and without the name configuration but nothing changed.

My travis config is:

https://github.com/codenamephp/chef.cookbook.bash/blob/bd37ebfd565f9e20b5c74c1abff0a346f69777a2/.travis.yml#L32
```
deploy:
  provider: chef-supermarket
  user_id: "codenamephp"
  client_key: "codenamephp.pem"
  name: "codenamephp_bash"
  category: "Utilities"
  edge: true
  cleanup: false
  run:
    - chef exec berks upload
  on:
    tags: true
```

Deployment previously worked with stove so I don't think the metadata.rb has problems.

Are there any obvious issues on my end or is this a bug in the parsing?
