### ISSUE TITLE
dpl v2 makes same named releases for each of my GitHub releases deployments

### ISSUE THREAD

**Issue by MarkCallow** [travis-ci/dpl#1213]
I deploy both Linux & macOS assets in my CI build when building for a tag. When using dpl v1 this works fine. All assets are uploaded to a single release named for the tag. In order to use the `release_notes` feature I switched to dpl v2. Now I get *two* releases both with the name of the tag.

Here is the dpl v1 deployment that works:

```yaml
  - provider: releases
    #edge: true # Use bleeding edge (dplv2)
    api_key: $GITHUB_TOKEN  # Set in the repo settings page as a secure variable
    file_glob: true
    file:
      - build-macos/KTX-Software-*.pkg
    skip_cleanup: true
    draft: true
    prerelease: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
  - provider: releases
    #edge: true # Use bleeding edge (dplv2)
    api_key: $GITHUB_TOKEN  # Set in the repo settings page as a secure variable
    file_glob: true
    file:
      - build-linux-release/KTX-Software-*-Linux.*
      - build-web-release/KTX-Software-*-Web-*.zip
    skip_cleanup: true
    draft: true
    prerelease: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
```

If I uncomment the 2 `edge: true` lines so it uses dpl v2, I get the 2 same-named releases I mentioned. 

Here's an example.

The project's Releases page:

![image](https://user-images.githubusercontent.com/2244683/92818162-3d68e400-f37c-11ea-9c3b-efa5fac13864.png)

The first release:

![image](https://user-images.githubusercontent.com/2244683/92818181-435ec500-f37c-11ea-9e1e-5ef5dd605dc0.png)

The second release:

![image](https://user-images.githubusercontent.com/2244683/92818208-4954a600-f37c-11ea-9d8f-204d95d64b45.png)

I am confused that Existing Tag is checked yet the text field above shows untagged with a different commit in each.

This issue is identical to that described in https://github.com/travis-ci/travis-ci/issues/10230 though given the age of the issue think it is talking about dpl v1, with which I am not having the problem.
