### ISSUE TITLE
Travis infinite loop

### ISSUE THREAD

**Issue by bmartinez287** [travis-ci/dpl#1215]
```
after_success: 
   - git add .
   - git commit -m "[skip travis] Adding particle dist/ assets"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: ${GITHUB_API_KEY}  # Your GitHub token set in Travis CI console
  target_branch: develop        # Add this line - To push into GitHub master branch
  on:
    branch: develop
```
The Travis deploy for the dist assets keeps triggering the Travis bot on the develop branch infinitely. How do I set a conditional to tell it to run once per merge PR?

In other words, I want to accomplish the following.
Merge the PR and automatically compile and commit the dist folder with its changes.
That said I only need that to happen once. Right now that triggers the Travis bot on a loop.
