### ISSUE TITLE
Unable to override `url` parameter in the `pages` provider when using `deploy_key`.

### ISSUE THREAD

**Issue by greglanthier** [travis-ci/dpl#1237]
I'm trying to deploy a site to a corporate GitHub Enterprise instance using the [`pages`](https://docs.travis-ci.com/user/deployment-v2/providers/pages) provider.

I run into problems when I try to use a `deploy_key`.

I've added the [`travis pubkey`](https://docs.travis-ci.com/user/encryption-keys/#fetching-the-public-key-for-your-repository) to the repo deploy keys with write access.

My `.travis.yml` has a stanza that looks like this:

```yml
deploy:
  # Use https://docs.travis-ci.com/user/deployment-v2/providers/pages/
  - on:
      branch: main
    provider: pages:git
    local_dir: ./public
    deploy_key: /home/travis/.ssh/id_rsa
    url: github.ibm.com
    verbose: true
    edge: true
```

When my builds run I see the following errors on the console:

```bash
Warning: apt-key output should not be parsed (stdout is not a terminal)
Gem 'dpl' is not installed
2.47s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl --pre
Fetching dpl-2.0.2.beta.1.gem
Fetching cl-1.2.4.gem
Fetching regstry-1.0.15.gem
Successfully installed regstry-1.0.15
Successfully installed cl-1.2.4
Successfully installed dpl-2.0.2.beta.1
3 gems installed
dpl.1
2.00sInstall deployment dependencies
Installing deployment dependencies
Installing gem dependencies: octokit (~> 4.15.0), public_suffix (~> 3.0.3)
dpl.2
0.00sAuthenticate deployment
Moving deploy key /home/travis/.ssh/id_rsa to ~/.dpl/deploy_key
Setting up git-ssh
Checking deploy key
$ ssh -i ~/.dpl/deploy_key -T git@github.com 2>&1 | grep successful > /dev/null
Failed to authenticate using the deploy key
failed to deploy
```

It looks like the check_deploy_key routine hard codes the `git@github.com` url in the check.

https://github.com/travis-ci/dpl/blob/85342e2e2ff42d20ad9881a7358788838addaa95/lib/dpl/providers/pages/git.rb#L61

Should this read something like this instead?

```ruby
check_deploy_key:    'ssh -i %{key} -T git@%{url} 2>&1 | grep successful > /dev/null', 
```
