### ISSUE TITLE
AWS Lambda Deployment gives "An update is in progress for resource" error

### ISSUE THREAD

**Issue by wolodarsky** [travis-ci/dpl#1246]
This has been highlighted here: https://travis-ci.community/t/dpl-lambda-fails-to-deploy-an-update-is-in-progress-for-resource/12424 but not seeing any issues open on GitHub.

There is a workaround to use CloudFormation, but this isn't feasible as we would need to reconfigure over 20 Lambdas to use CloudFormation,

I wanted to open the issue here because this is where I came to look for it and found no open issue.

**Comment by scottgeye** [comment]
Any updates?  Seems like this should be a high priority issue since it breaks lambda deployments that were previously working.

**Comment by wolodarsky** [comment]
@scottgeye We're looking into moving our deployments away from dpl as this has been a big issue for production deployments and we're not sure the dpl team is able to look into this issue. The suggestion from Travis support was to use CloudFormation templates which requires significant rework to all of our CI.

We're considering moving to one of the following for Lambda deployments: 
 - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html or  
 - https://www.serverless.com/

**Comment by scottgeye** [comment]
Moving to cloud formation is pretty aggressive for us.  I was able to put together a simple deploy script that worked with node using node-lambda from npm (https://github.com/motdotla/node-lambda)

Example travis file:

```
language: node_js
node_js:
  - "lts/*"
 
script:
  - npm i -g node-lambda

deploy:
  - provider: script
    script: node-lambda deploy -G src -p true -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -r $LAMBDA_REGION -n $LAMBDA_NAME_DEV -o $LAMBDA_ROLE_DEV
    skip_cleanup: true
```
