### ISSUE TITLE
error installing dpl

### ISSUE THREAD

**Issue by Indecis1** [travis-ci/dpl#1248]
Hello. I have a spring boot project. I last compiled it 8 days ago, but today I compile it and I have this error when travis want to deploy my project on Heroku. 

**Log**
![deploy_error](https://user-images.githubusercontent.com/80837432/148236518-3f327c2d-ff9a-45cc-95e6-0574e2d2c99b.PNG)

**.travis.yml**
<pre>
language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - rvm install 2.7.0
  - rvm use 2.7.0
  - ruby -v
  - gem install dpl --pre

script:
  - mvn clean verify
 
deploy:
  provider: heroku
  api_key:
    secure: [myEncryptedKey]
  app: [project_name_on_heroku]
  on:
    repo: [repo_name_on_github]
    branch: main
</pre>

**Comment by colindean** [comment]
Your screenshot shows that the current Ruby version is 2.4.5. That's the `${travis_internal_ruby}`. You might need to set up your deploy step in a separate step kinda like GitLab users do in their `.gitlab.yaml`:

```yaml
deploy_staging:
  stage: deploy
  type: deploy
  image: ruby:latest
  script:
  # workaround https://github.com/travis-ci/dpl/issues/1247
  - gem install dpl && gem install faraday -v 1.8.0
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_API_KEY
  except:
  - schedules
  only:
  - merge_requests
```

You'll have to translate that to the equivalent in Travis config, though, obviously.
