### ISSUE TITLE
deploy to github pages report no deploy_key

### ISSUE THREAD

**Issue by zhjwpku** [travis-ci/dpl#1261]
Following are the deploy config:

```
deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: book # In case of custom book path: path/to/mybook/book
  keep-history: false
  on:
    branch: master
  target_branch: gh-pages
```

dist xenial and bionic both report the following error:

![image](https://user-images.githubusercontent.com/12639404/173193163-3020bebc-feb6-4a3a-b24c-e7cfdb346818.png)
