### ISSUE TITLE
Github release is failing as tag_name is not set

### ISSUE THREAD

**Issue by Pezmc** [travis-ci/dpl#136]
Running DPL github release directly from travis with:

```
deploy:
  provider: releases
  api_key:
    secure: very long key here...
  file: remotetech2-build${TRAVIS_BUILD_NUMBER}.zip
  release-number: ${BUILDTAG}-alpha-build${TRAVIS_BUILD_NUMBER}
  on:
    repo: Pezmc/RemoteTech
```

The tag_name is not getting set as `git describe --tags --exact-match 2>/dev/null` returns null as the current commit doesn't have an asossiated tag.

`git describe --abbrev=0 --tag` shows the most recent tag as `v1.0.0-alpha0.1` but it digging in the dpl code it looks like there's no way to set the tag_name directly.

Full error in console:

```
Users/travis/.rvm/gems/ruby-1.9.3-p484/gems/octokit-3.1.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/Pezmc/RemoteTech/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: missing_field
  field: tag_name
  resource: Release
  code: custom
  field: tag_name
  message: tag_name is not well-formed
  resource: Release
  code: custom
  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release
```
