### ISSUE TITLE
Add support for different Cache-Control headers for S3 deploy 

### ISSUE THREAD

**Issue by bulyshko** [travis-ci/dpl#167]
It would be awesome if S3 deploy could add different Cache-Control headers. Syntax could be:

``` yaml
deploy:
  cache_control:
  - max-age=2592000
  - no-cache:
    - index.html
```

It would also work for things like `expires` to specify different values:

``` yaml
deploy:
  expires:
  - "2015-01-01 00:00:00 -0000":
    - "assets/**/*.js"
    - "assets/**/*.css"
  - "2020-01-01 00:00:00 -0000":
    - "**/*.png"
    - "**/*.jpg"
    - "**/*.gif"
```

**Comment by klaemo** [comment]
This doesn't currently work as expected. All files get `max-age=2592000`.

**Comment by bulyshko** [comment]
Will investigate.

**Comment by ivanbreet** [comment]
Experiencing the same issue. index.html gets a max-age even though it’s listed under no-cache.

```
deploy:
  cache_control:
  - max-age=2592000
  - no-cache:
    - index.html
```
