### ISSUE TITLE
GAE SDK download does not exist

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/dpl#179]
The URL used to download the GAE SDK seems to be expired: https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/gae.rb#L25. 

As far as I understand they've deprecated this version? https://console.developers.google.com/storage/appengine-sdks/deprecated/1910/

**Comment by Trii** [comment]
@BanzaiMan you can use the updatecheck URL to dynamically determine the latest version number.

https://appengine.google.com/api/updatecheck
```
release: "1.9.19"
timestamp: 1424415497
api_versions: ['1']
supported_api_versions:
  python:
    api_versions: ['1']
  python27:
    api_versions: ['1']
  go:
    api_versions: ['go1']
  java7:
    api_versions: ['1.0']
```

I implemented a similar feature for a zc.buildout recipe for python https://github.com/prmtl/appfy.recipe.gae/pull/21
