### ISSUE TITLE
npm deploy only master branch

### ISSUE THREAD

**Issue by djindjic** [travis-ci/dpl#214]
Am I doing something wrong if I make some changes on master branch in my github repo followed by this commands:
```bash
git add --all
git commit -m "update"
git tag v0.0.1
git push origin master
git push origin --tags
```

my .travis.yml is:
```yml
deploy:
  provider: npm
  email: me@email.com
  skip_cleanup: true
  api_key:
    secure: '...'
  on:
    tags: true
    repo: user/repo
```
It fails with `Skipping deployment with the npm provider because this branch is not permitted to deploy`, but am I just tagged latest commit on master branch? Why I need to include all_branches: true into configuration if I didn't make any new branch?

I have tried it with both annotated and lightweight tags described in [git docs](http://git-scm.com/book/en/v2/Git-Basics-Tagging#Creating-Tags) and had same problem.

I don't want to run travis build for other branches, especially in this case because when I push this commit and tag to github, travis starts two builds, one for commit and other for tag itself
