### ISSUE TITLE
Gem with Gemspec file named `.gemspec` cannot be deployed

### ISSUE THREAD

**Issue by dalen** [travis-ci/dpl#220]
If I set the gemspec option to `.gemspec` in the rubygems provider it will only upload gems matching `-*.gem`.

As the gemspec method will then return `''` and that will cause the glob to match `"-*.gem"` which won't match the gem correctly.

**Comment by BanzaiMan** [comment]
Sorry for the delay. Are you saying that you have this?

```yaml
deploy:
  provider: rubygems
  gemspec: .gemspec
```

I am not sure how you are expecting this to work.
