### ISSUE TITLE
Elastic beanstalk doesn't deploy to correct path

### ISSUE THREAD

**Issue by dieend** [travis-ci/dpl#276]
In my `.travis.yml` I have these lines:
```
deploy:
  provider: elasticbeanstalk
  access_key_id: ACCESS_KEY
  secret_access_key: SECRET_KEY
  region: ap-southeast-1
  app: testapp
  env: testapp-env
  skip_cleanup: true
  bucket_name: bucketbeanstalk
  bucket_path: travis-beanstalk/
  on:
    repo: testuser/travis-beanstalk
    branch: master 
```

My apps is deployed correctly. But instead of saving the zip to `s3://bucketbeanstalk/travis-beanstalk/travis-commit_hash-timestamp.zip`, it's saving the zip to `s3://bucketbeanstalk/travis-commit_hash-timestamp.zip`. Any idea why?
