### ISSUE TITLE
RFC: fine-grained cache-control

### ISSUE THREAD

**Issue by jamesarosen** [travis-ci/dpl#287]
## Summary

Specifically for the [gcs provider](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/gcs.rb), I'd like to add more fine-grained control over cache-control. I'm happy to make a PR for the feature, but I wanted to run it by you first to see if you had any thoughts on the API or implementation.
## Use-Case

I'm using Travis to build an Ember application. I want to cache fingerprinted assets forever (i.e. 1 year) and a handful of other things (e.g. `index.html`, `robots.txt`) for 30 seconds.
### Idea 1: Match Strings

``` yml
// .travis.yml
deploy:
  provider: s3
  local_dir: "dist/"
  cache_control:
    "dist/index.html": "max-age=30" # relative to project root? or local_dir?
    "*.css,*.js,*.svg,*.ttf,*.woff,*.woff2": "max-age=31536000"
    "*": "no-cache"
```

It might be better to make that an Array instead of a Hash so the matches are strictly ordered:

``` yml
cache_control:
  - match: "dist/index.html"
    value: "max-age=30"
  - match: "*.css,*.js,*.svg,*.ttf,*.woff,*.woff2"
    value: "max-age=31536000"
  - match: "*"
    value: "no-cache"
```

Given that the provider [changes to the `local_dir` before globbing](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/gcs.rb#L31-L32), I suspect the matches should be against the path relative to `local_dir`. (Otherwise you'd just have to prepend `local_dir` back onto the path when checking against the matches.)
### Idea 2: Arbitrary Script

``` yml
// .travis.yml
deploy:
  provider: s3
  local_dir: "dist/"
  cache_control_generator: "lib/cache_control_for.rb"
```

``` rb
# lib/cache_control_for.rb
#!/usr/bin/env ruby

case ARGV[0]
when "dist/index.html" # again, relative to project root? local_dir?
  puts "max-age=30"
when /\.(css|js|svg|ttf|woff2?)$/
  puts "max-age=31536000"
else
  puts "no-cache"
end
```
## Alternative Implementations
1. I could upload everything with a short cache expiry or `no-cache` and then use a secondary script to manipulate the `Cache-Control` headers in Google Cloud Storage afterwards. This isn't great because Travis overwrites existing files when it uploads, so if I had an existing fingerprinted asset, its `Cache-Control` would toggle every time the deploy hook fired.
2. Since I'm serving the GCS bucket through [Varnish](https://www.varnish-cache.org/) (via [Fastly](https://www.fastly.com/)), I could have Travis set `Cache-Control: no-cache` and override that in `vcl_fetch`. But I don't love that the GCS bucket essentially "lies" to the cache.
