### ISSUE TITLE
Deploy to supermarket doesn't work

### ISSUE THREAD

**Issue by evtuhovich** [travis-ci/dpl#303]
When use supermarket provider with such a config
````
deploy:
  edge: true
  provider: chef-supermarket
  user_id: express42
  client_key: ".travis/express42.pem"
  cookbook_category: Monitoring & Trending
  skip_cleanup: true
  on:
    tags: true
````

got en error. I think opscode (and now chef) change the API endpoint.

````
Uploading to http://cookbooks.opscode.com/api/v1/cookbooks
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.18.12/lib/chef/json_compat.rb:50:in `rescue in parse': lexical error: invalid char in json text. (Chef::Exceptions::JSON::ParseError)
                                       <html>  <head><title>301 Moved 
                     (right here) ------^
````
