### ISSUE TITLE
Deis not able to take the cli_version dynamically since #297

### ISSUE THREAD

**Issue by kalbasit** [travis-ci/dpl#315]
For some reason, since #297 was merged and released this is no longer working for me:

.travis.yml (notice the before_deploy section):

```
language: node_js

# Runtime
node_js:
  - '0.10'

# Directories to persist between builds (deps)
cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - cp .netrc ~/.netrc
  - git config --global url."https://github".insteadOf git://github

install:
  - gem install compass
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g grunt grunt-cli bower yo generator-karma generator-angular
  - npm install
  - bower install

before_deploy:
  # Workaround travis-ci/dpl#240
  - export PATH="$PATH:$HOME/.local/bin"
  - export DEIS_PLATFORM_VERSION=`curl -sD- deis.example.com | grep '^DEIS_PLATFORM_VERSION' | cut -d\  -f2` && echo $DEIS_PLATFORM_VERSION

deploy:
  # The prod application, deployed from the production branch.
  - provider: deis
    cli_version: $DEIS_PLATFORM_VERSION
    controller: deis.example.com
    app: console
    username: deis_deployer
    password:
      secure: ...
    on:
      repo: example/console
      branch: production
  # The dev application, deployed from the master branch.
  - provider: deis
    cli_version: $DEIS_PLATFORM_VERSION
    controller: deis.example.com
    app: console-dev
    username: deis_deployer
    password:
      secure: ...
    on:
      repo: example/dmx-console
      branch: master

```

This used to work correctly and always install the client version that matches the server, but ever since this change I get this on Travis:

```
$ export PATH="$PATH:$HOME/.local/bin"
$ export DEIS_PLATFORM_VERSION=`curl -sD- deis.example.com | grep '^DEIS_PLATFORM_VERSION' | cut -d\  -f2` && echo $DEIS_PLATFORM_VERSION
1.9.0
Fetching: dpl-1.7.20.gem (100%)
Successfully installed dpl-1.7.20
1 gem installed
Installing deploy dependencies
missing client_version
failed to deploy
```

Original comment [here](https://github.com/travis-ci/dpl/commit/11fa53f06493d3c7c53fb696b54833a2f08a1d0e#diff-140db6e9f61f634ad4cf1cc7adce57a1)
