### ISSUE TITLE
error: src refspec master does not match any when deploying to OpenShift

### ISSUE THREAD

**Issue by AFusco** [travis-ci/dpl#331]
This is in my `.travis.yml` file:

```
sudo: false
language: node_js
node_js:
  - '0.10'
env:
  global:
  - GH_REF: github.com/AFusco/MyRepo.git
  - secure: (hidden)
install: "./scripts/install_dependencies.sh"
cache:
   directories:
    - node_modules
    - bower_components

deploy:
  provider: openshift
  skip_cleanup: true
  user: myname@gmail.com
  password:
    secure: (hidden)
  domain: correct_openshift_namespace
  app:
    master: staging
    production: production
after_success: 
  - ./scripts/deploy_app.sh
```

the deploy script run after success is:

```
#!/bin/bash
set -ev

rm -rf ./dist
grunt build
cd ./dist
git init
git status
git config --global push.default simple
git config --global user.email "travis@travis-ci.com"
git config --global user.name "Travis CI"
git checkout -b master
git add --all
git commit -am "Travis deploy"
```

The thing is: when it comes to pushing the code I get this error, just as it would if nothing had been committed. 

```
deployment_branch detected: master
Warning: Permanently added 'staging-latenight.rhcloud.com' (RSA) to the list of known hosts.
error: src refspec master does not match any.
error: failed to push some refs to 'ssh://55f0ca6189f5cfc32600010c@staging-namespace.rhcloud.com/~/git/staging.git/'
Done. Your build exited with 0.
```

What am I doing wrong?
