### ISSUE TITLE
codedeploy options in env not found

### ISSUE THREAD

**Issue by cedwards-reisys** [travis-ci/dpl#335]
Created the following env vars:

AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

in build settings and set them to private.

Get "missing access_key_id" message in build.

https://travis-ci.org/REI-Systems/REISystems-OG-DejaVu

**Comment by BanzaiMan** [comment]
Please test the fix with:

```yaml
deploy:
  provider: code_deploy
  edge: true # <= new!
  ⋮ # rest
```

I plan a release next week (at which point you can drop `edge: true`).
