### ISSUE TITLE
script provider don't work with bundler on travis

### ISSUE THREAD

**Issue by timoschilling** [travis-ci/dpl#336]
I want to deploy with Capistrano after a Travis build.

I have tried some different thinks:
A. This results in a `bundler: command not found: cap` error

``` yaml
deploy:
  provider: script
  script: bundle exec cap integration deploy
  on:
    branch: master
```

B. This results in the same error on Travis but works on my local machine:

``` yaml
after_success: "[[ $TRAVIS_BRANCH = 'master' ]] && gem install dpl && dpl --provider=script --script='bundle exec cap integration deploy'"
```

C. This works

``` yaml
after_success: "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap integration deploy"
```
