### ISSUE TITLE
Multiple deployments with a edge: source fail

### ISSUE THREAD

**Issue by jasny** [travis-ci/dpl#342]
I'm using my own fork of dpl using [this guide](https://github.com/travis-ci/dpl/blob/master/TESTING.md).

However when I use two deployments with a source for `edge`, the second deployment fails. Unfortunately without giving any error as output.

When I manually download and install [jasny/dpl](http://github.com/jasny/dpl) and using `edge: local`, I don't have the problem.

**Comment by jasny** [comment]
@BanzaiMan

This is what the deploy section of my .travis.yml looks like.

```
deploy:
# Staging
- provider: elasticbeanstalk
  edge:
    source: jasny/dpl
    branch: master
  access_key_id: xxxx
  secret_access_key:
    secure: xxxx
  region: eu-west-1
  app: myapp
  bucket_name: elasticbeanstalk-eu-west-1-123456789012
  bucket_path: myapp
  on:
    all_branches: true
    condition: '"${TRAVIS_BRANCH:0:7}" != "travis-"'

# Production
- provider: elasticbeanstalk
  edge:
    source: jasny/dpl
    branch: master
  access_key_id: xxxx
  secret_access_key:
    secure: xxxxx
  region: eu-west-1
  app: myapp
  bucket_name: elasticbeanstalk-eu-west-1-012012012012
  bucket_path: myapp
  upload_only: true
  on:
    branch: master
```
