### ISSUE TITLE
Elastic Beanstalk: The bucket name parameter must be specified when requesting an object

### ISSUE THREAD

**Issue by liddellj** [travis-ci/dpl#347]
Today my deployment script started failing as follows:
```
Preparing deploy

Deploying application

/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in `return_or_raise': The bucket name parameter must be specified when requesting an object (AWS::ElasticBeanstalk::Errors::InvalidParameterValue)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `update_environment'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider/elastic_beanstalk.rb:140:in `update_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider/elastic_beanstalk.rb:42:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider.rb:143:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider.rb:143:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

Here's the relevant snippet of my `travis.yml`:
```
deploy:
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].[0-9].[0-9]$"
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  app: <my-app-name>
  env: <my-env-name>
  zip-file: Dockerrun.aws.json
  skip_cleanup: true
  bucket_name: <my-bucket-name>
  bucket_path: docker
```

I've obfuscated sensitive details from the above, but rest assured - `bucket_name` refers to a valid S3 bucket - and this setup was working recently. The only thing I've changed recently of note is the base image for the Dockerfile, but I can't see how that's might have caused this.

Has something changed in the dpl that somehow makes my config invalid? I last deployed to Elastic Beanstalk through Travis on the 23rd September at 10:15 (UTC) without issue. I've tried re-running the build a few times but the issue persists.

In case it is of relevance, I'm using Travis Pro.
