### ISSUE TITLE
invalid option "--file="

### ISSUE THREAD

**Issue by petemoore** [travis-ci/dpl#371]
See [this build](https://travis-ci.org/taskcluster/livelog/jobs/93372806#L464-L468):

```
Fetching: dpl-1.8.11.gem (100%)
Successfully installed dpl-1.8.11
1 gem installed
invalid option "--file="
failed to deploy
```

The [deploy section](https://github.com/taskcluster/livelog/blob/1524b2a767d7dfe8f376cbf01c649f2fe0943658/.travis.yml#L33-L42) of travis.yml looks like this:

```
deploy:
  provider: releases
  api_key:
    secure: fwTLVhfs/5ioduZQdj49n6/4rn7AYcAyAeUcRdA/ezhWAj1KsT6qU7snBdhfEwpo+TaVbLq6SwpknLXax9d6mESs7EOL9EmEt73ocw0OG1omfjrBn5mQuuVIiUky5qhIZy+qufiqUq3iVe/V8cyZSGqcPRbazLIhAAKR0r44dys=
  file:
    - "${RELEASE_FILE}"
  on:
    repo: taskcluster/livelog
    tags: true
  skip_cleanup: true
```

Perhaps this is related to using the environment variable `${RELEASE_FILE}` - however this has been working without problem in the past in another project.

[.travis.yml excerpt](https://github.com/taskcluster/generic-worker/blob/e853c6b190729ff38d0d24eec01389d2ffb6f871/.travis.yml#L34-L43):

```
deploy:
  api_key:
    secure: KuifEWzfB5C9GFHMjFpSpbHWLN9cs/1afRuJhP4aADU3i55zb0QDzIu6+aGLlL0jsV5T07AqgPvJm4bOQNnWVhlhyHStrkIdzUpCtiCVNnPH3cYUkJ4/0zJyJaopnZfuX/2m2F+ajNC2Z94mxuu4qUUgqFO9x708xy0LYCofTEU=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: taskcluster/generic-worker
    tags: true
```

[Successful deploy](https://travis-ci.org/taskcluster/generic-worker/jobs/82891045#L218):

```
Deploying application
```
