### ISSUE TITLE
Add option to specify charset for S3

### ISSUE THREAD

**Issue by tschaub** [travis-ci/dpl#416]
I'm curious if it would be possible to support an option for specifying a charset to be added to the [`content_type` option](https://github.com/travis-ci/dpl/blob/2bf330d86c4503247815d0dd7a830882d9225888/lib/dpl/provider/s3.rb#L49) when uploading to S3.

I'd like to get `Content-Type: text/html; charset=utf-8` for all `*.html` for example.  Maybe even any place `MIME::Types.type_for(filename).first.binary` is `false`.

**Comment by colin-air** [comment]
You may already know this, but you can set a default charset

```yml
- provider: s3
  default_text_charset: utf-8
```

The result here is that **all** text files would have this appended to their `Content-Type` e.g. HTML -> `text/html; charset=utf-8` and Javascript files -> `application/javascript; charset=utf-8`

But I agree that fine grained control would be a nice feature e.g.

```yml
- provider: s3
  default_text_charset: utf-8    # Catch all / global default
  text_charset:
    - "*.html": utf-8
    - "*.css": iso-8859-1
    - "*.rtf": utf-16
```
