### ISSUE TITLE
error: unable to push to unqualified destination: master

### ISSUE THREAD

**Issue by kahwooi** [travis-ci/dpl#421]
I am using Gitab-CI to deploy my application to Azure website:

```
deploy_prod:
  stage: deploy
  script: 
    - apt-get -qq update
    - apt-get install -yqq ruby ruby-dev
    - gem install dpl
    - dpl --provider=AzureWebApps --username=$AZURE_WA_USERNAME --password=$AZURE_WA_PASSWORD --site=xxx --verbose
  only:
    - master
```

I got this error:

```
Deploying application
Deploying to Azure Web App 'xxx'
error: unable to push to unqualified destination: master
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
```

Any reason why it is looking for refs? How to solve this problem?
