### ISSUE TITLE
Deployment doesn't recognise variables in file names.

### ISSUE THREAD

**Issue by kenorb** [travis-ci/dpl#423]
I've [`.travis.yml`](https://github.com/FX31337/FX-BT-Data-EURUSD-DS/blob/a78c52f0eee3b177032c3bb1d1fef2aa5c586127/.travis.yml) where file having some variables which were defined in global:

```
env:
  global:
    - pair=EURUSD
deploy:
  provider: releases
  api_key:
    secure: MYKEY
  file:
    - "$(pair)1.hst.gz"
    - "$(pair)5.hst.gz"
```

However these aren't recognised.

```
Fetching: dpl-1.8.14.gem (100%)
Successfully installed dpl-1.8.14
1 gem installed
/home/travis/build.sh: line 45: pair: command not found
/home/travis/build.sh: line 45: pair: command not found
/home/travis/build.sh: line 45: pair: command not found
```

Build: [#119701340](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/jobs/119701340)

Is that a feature or bug?
