### ISSUE TITLE
after_failure hook not triggered after failing build

### ISSUE THREAD

**Issue by andreylushchick-planorama** [travis-ci/dpl#447]
I have a simple script deployment that exits with 1 status. I expect that after_failure hook will be triggered, but it's not. `.travis.yml`:

``` yaml
sudo: false
language: node_js
node_js: '4'

deploy:
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh

after_deploy:
  - echo "after_deploy"

after_failure:
  - echo "after_failure"

after_script:
  - echo "after_script"
```

`deploy.sh`:

``` bash
#!/usr/bin/env bash
echo "test"
exit 1
```

I'm just getting an error and that's it:

```
Script failed with status 1
failed to deploy
```

Test build: [130075818](https://travis-ci.org/andreylushchick-planorama/playground/builds/130075818)
