### ISSUE TITLE
Precompiled assets were not packaged with provider 'elastic beanstalk'

### ISSUE THREAD

**Issue by sebastienliu** [travis-ci/dpl#478]
I am using travis-ci to build assets for my rails app, but the precompiled assets by Travis seemed to be cleaned up and were not zipped to a package. I downloaded the zip file Travis deployed to Elastic Beanstalk, there is no 'asset' folder.

My .travis.yml file is:

```
language: ruby
rvm:
- 2.3.0
before_script:
- createdb sample_app_db
- bundle exec rake db:schema:load
cache: bundler
services:
- memcached
addons:
  postgresql: 9.4

after_success:
  - bundle exec rake assets:precompile

deploy:
- provider: elasticbeanstalk
  app: sample-website
  env: sample-website-staging
  bucket_name: sample-s3bucket
  skip_cleanup: true
  region: ap-southeast-2
  access_key_id:
    secure: 'key'
  secret_access_key:
    secure: 'key'
  on:
    branch: staging
```
