### ISSUE TITLE
throw cannot remove directory when run my custom dpl provider

### ISSUE THREAD

**Issue by forhot2000** [travis-ci/dpl#481]
Hi,

I have customized a provider to deploy to AWS ECS, but my custom dpl project can't be passed in travis.

here is the tail of the travis build logs, my provider code never called `rm` command, I don't know who are calling the `rm` command.

```
Cloning into 'Misfit-SW-China/dpl'...
remote: Counting objects: 5798, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 5798 (delta 21), reused 0 (delta 0), pack-reused 5752
Receiving objects: 100% (5798/5798), 1.81 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3432/3432), done.
Checking connectivity... done.
/tmp/Misfit-SW-China/dpl /tmp ~/build/Misfit-SW-China/dpl
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
WARNING:  pessimistic dependency on rspec (~> 3.0.0, development) may be overly strict
  if rspec is semantically versioned, use:
    add_development_dependency 'rspec', '~> 3.0', '>= 3.0.0'
WARNING:  open-ended dependency on rspec-its (>= 0, development) is not recommended
  if rspec-its is semantically versioned, use:
    add_development_dependency 'rspec-its', '~> 0'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
WARNING:  open-ended dependency on coveralls (>= 0, development) is not recommended
  if coveralls is semantically versioned, use:
    add_development_dependency 'coveralls', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: dpl
  Version: 1.8.18.travis.28.1
  File: dpl-1.8.18.travis.28.1.gem

/tmp ~/build/Misfit-SW-China/dpl
rm: cannot remove directory: `.'
The command "rm -rf ." failed and exited with 1 during .
Your build has been stopped.
```

and the `deploy` section in `.travis.yml` is

```
deploy:
  - provider: ecs
    edge:
      source: $TRAVIS_REPO_SLUG
      branch: $TRAVIS_BRANCH
    skip_cleanup: true
    docker_image: $DOCKER_IMAGE:$DOCKER_TAG
    environment: staging
    environment_prefix: ECS_STG_
    access_key_id: XXXXXXXXXXDNBFHTYIYA
    secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXPiALo5DuGaLt9j/R
    dry_run: true
    on:
      repo: Misfit-SW-China/dpl
      all_branches: true
```
