### ISSUE TITLE
Issue deploying branches to multiple gears.

### ISSUE THREAD

**Issue by Karn** [travis-ci/dpl#502]
Hello,

I've been experiencing an issue where having multiple branches to deploy to corresponding OpenShift gears fails. In my case, having two branches `master` and `develop` and wanting to deploy to the gears `prod` and `dev` respectively only works when travis completes a successful build of `master`. Conversely, if travis builds the `develop` branch, it does not deploy and i'm presented with the following message, and no changes are deployed.

``` Bash
Warning: Permanently added 'dev-********.rhcloud.com' (RSA) to the list of known hosts.
Everything up-to-date
```

However, if you manually deploy to the `dev` gear using the dpl-cli it works.
I may have an incorrect config file as the documentation on the travis docs page seems incomplete, as such I have provided an excerpt of my `.travis.yml` file below.

``` Yaml
language: node_js
node_js:
  - '4.4'
before_script:
  - npm install grunt-cli -g
  - npm run build
deploy:
  provider: openshift
  domain: *********
  skip_cleanup: true
  user: *********
  password:
    secure: *********
  app:
    develop: dev
    master: prod
```

Cheers!

**EDIT**: The issue seems to have been resolved by performing a [manual dpl-cli deploy](https://github.com/travis-ci/dpl#openshift). Travis is now deploying properly.
I'm not sure what the next steps are for this issue.

**Comment by BanzaiMan** [comment]
Try using 2 deployment providers, both of which are OpenShift.

```yaml
deploy:
  - provider: openshift
    domain: *********
    skip_cleanup: true
    user: *********
    password:
      secure: *********
    app:
      develop: dev
  - provider: openshift
    domain: *********
    skip_cleanup: true
    user: *********
    password:
      secure: *********
    app:
      master: prod
```
