### ISSUE TITLE
Corrupt Zip file from Travis when using EB Provider 

### ISSUE THREAD

**Issue by jvmontes** [travis-ci/dpl#532]
After compiling our application with TravisCI we intend to upload the contents of our generated `dist` folder. As seen for other AWS providers we are currently doing this by using the `before_deploy` hook to cd into the `dist` directory. 

We have verified the contents of this folder after changing to this directory but when the DPL script does the upload to S3 we’ve noticed that the zip file that is uploaded appears to be corrupt. We have attempted to download the zip file from the EB Application Versions page in AWS and still have issues unpacking the uploaded zip file. 

When initially testing without `cd`ing into a subdirectory we did not see any issues related to corrupted zip files. This issue can potentially be tracked down to the `create_zip` method found in the elasticbeanstalk provider but without extensive ruby knowledge I thought bringing up the issue here might be able to shed some light.

```yaml
before_deploy:
  - cd dist
  - ls
deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    region: us-west-2
    app: MyApp
    env: my-env
    bucket_name: my-bucket
    access-key-id: "$ACCESS_KEY_ID"
    secret-access-key: "$SECRET_ACCESS_KEY"
  on:
    branch: my-branch
```

Thanks in advance,

**Comment by briananderson1222** [comment]
@jvmontes 

Not sure where exactly the issue lies in the dpl code but I have found that adding

```
before_deploy:
  - cd dist
  - zip -r archive.zip *

deploy:
  - provider: elasticbeanstalk
    zip_file: archive.zip
    ...
```

and using the provided `zip_file` option for the provider seems to be a valid workaround to this issue.
