### ISSUE TITLE
Expected merge order behavior for multiple instances of a single provider

### ISSUE THREAD

**Issue by davidski** [travis-ci/dpl#559]
I'm trying to create a `.travis.yml` which will deploy all commits on a dev branch to a test PyPi server while all tags on master go to the live PyPi server. Issue #266 suggests that these sort of multiple instances of a single provider deployments are doable, though the final comment about order being important seems to mirror my experience.

In a sample job (https://travis-ci.org/davidski/VulnPryer/jobs/186403908), `dpl` tried to deploy to the live PyPi site and ignored the test configuration, which is just the opposite of what I intended.  The section of the `.travis.yml` used (full version at https://github.com/davidski/VulnPryer/blob/8d0e02b34a4aa59d75cfef54ca82c7471986008b/.travis.yml) is

```
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: davidski
    skip_cleanup: true
    password:
      secure: CUT_FOR_SPACE
      on:
      branch: dev
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
      
  - provider: pypi
    user: davidski
    skip_cleanup: true
    password:
      secure: CUT_FOR_SPACE
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
```

I've tied numerous versions of this pattern and it seems like the last stanza wins for parameters like password, server URL, etc. 

How are options for multiple instances of a single provider intended to work? Is this a supported use case?
