### ISSUE TITLE
deploy provider does not receive Hash configuration options

### ISSUE THREAD

**Issue by adamkingit** [travis-ci/dpl#587]
I started on an update to the CloudFoundry provider to allow it to accept environment variables to set on the application.  The idea is to allow something like the following to be used to set the variables. A CloudFoundry application manifest can define and deploy more than one application at once. The syntax below allows a variable to be set for all applications, or to just set the variables on a subset of the applications.
```
  - provider: cloudfoundry
    api: "https://api.ng.bluemix.net"
    manifest: manifest-us-stage.yml
    username: $BLUEMIX_USER
    password: "notmypwd"
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    skip_cleanup: true
    cfenv:
      env: 
        - "person=Jesse"
      app:
        names:
          - echo_vcap_stage
          - troll-gate
        env:
          - CF_REPO_SLUG: $TRAVIS_REPO_SLUG
          - CF_COMMIT: $TRAVIS_COMMIT
    on:
      branch: setenvs
```

I found that Hash options are not passed through to the dpl provider. I traced this back to https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/addons/deploy/script.rb#L164
but I am not quite able to follow why it treats any Hash as a lookup to data.branch

Would you give me a pointer where to look or where to ask?
