### ISSUE TITLE
Add deployment option for FTP

### ISSUE THREAD

**Issue by Stevoisiak** [travis-ci/dpl#611]
Currently, the recommended methods for deploying to an FTP server from Travis CI is either to [write a custom shell script](https://docs.travis-ci.com/user/deployment/script/) or run a [curl command](https://docs.travis-ci.com/user/deployment/custom/) in the 'after_success' section.

It'd be nice to have FTP supported as a deployment option. A minimal configuration for `.travis.yml` could resemble the following.
```
deploy:
  provider: ftp
  host: ftp://sitename.com/directory/myfile
  user: "FTP USERNAME"
  password: "FTP PASSWORD"
  skip_cleanup: true
  on:
    branch: master
```
