### ISSUE TITLE
Can't pass body option to Octokit

### ISSUE THREAD

**Issue by abitrolly** [travis-ci/dpl#657]
For some reason `body` option is not passed to Octokit and failing
```
invalid option "--body=Polish GitHub relea..."
```
https://travis-ci.org/cyberFund/xchange-crawler#L1378

Deployment setting
```
deploy:
  provider: releases
  api_key: ...
  file: $DISTZIP
  skip_cleanup: true
  # https://docs.travis-ci.com/user/deployment/releases/#Advanced-options
  prerelease: true
  name: "devbuild-$TRAVIS_BRANCH-$TRAVIS_COMMIT"
  body: "$TRAVIS_COMMIT_MESSAGE\n\n[skip ci]"
```
https://github.com/cyberFund/xchange-crawler/blob/26d495a1e4f70be5cf8c341ebe48aa821111f17a/.travis.yml#L28

From what I see Octokit is used as a library, so the problem must be in `dpl` option handling.
