### ISSUE TITLE
Execute multiple commands through the script provider

### ISSUE THREAD

**Issue by tdmalone** [travis-ci/dpl#673]
Would it be possible to have the ability to execute multiple commands with the script provider?

eg. `dpl --provider=script --script=./script/deploy.sh --script=./script/something-else.sh`

I realise this could already be achieved in one script argument by using ampersands or a semi-colon; I'm coming from the point of view of wondering if it's possible to construct travis.yml with multiple deploy scripts in the same syntax used elsewhere in the file.

For example, currently this does not work:

```
deploy:
  - provider: script
    script:
       - ./script/deploy.sh
       - ./script/something-else.sh
```

These two alternative syntaxes do:

```
deploy:
  - provider: script
    script:
       ./script/deploy.sh;
       ./script/something-else.sh
```

```
deploy:
  - provider: script
    script: ./script/deploy.sh && ./script/something-else.sh
```

However it would be nice to allow multiple commands similar to other scripts in the yaml.

**Comment by tdmalone** [comment]
unstale

**Comment by MichaelOrtho** [comment]
Yes, unstale. I think too this would be very valuable feature. I do not think it would be that big effort to change script provider to accept one or array of commands/scripts. Any comment? @BanzaiMan?

**Comment by tdmalone** [comment]
unstale

**Comment by colby** [comment]
Got bit by this today, would love to hear an update on status. Thanks!

**Comment by balazsorban44** [comment]
Is there any progress on this?

**Comment by tdmalone** [comment]
^ Unless I’m misunderstanding, I think this confuses the issue a little.

You don’t need before_deploy as a workaround for this. You just need to specify your script commands by joining them with && or ;

Or - as you mentioned - using an external script (it doesn’t need to be in the top level of your repo either - you could create a scripts or ci folder to hold whatever you need to).

**Comment by beamerblvd** [comment]
So, first of all, an external script is a non-starter for me. I know it's a possibility, but I want visibility into my entire build process in the single Travis file.

As for joining my script commands with `&&` or `;` ... I tried that. It only works if I have a single 300-character-long line in my file, which is practically unreadable. If I try to wrap it in any way (using any of the three methods of having multi-line strings in Yaml), I get errors that `ntar` is not a command. Somehow or another, the literal two characters "\n" are getting put between lines, instead of actual newlines (no, I'm not manually typing newline characters), in the command sent to the shell, resulting in every command starting with the letter `n` and rendering it unexecutable.

**Comment by beamerblvd** [comment]
Furthermore, even if all of the above worked and was fine with me, it's still a big deficiency, IMO. They're all just workarounds to an underlying problem: Everywhere else in the `.travis.yml` file, `script` is a sequence. To have it be not-a-sequence in this one spot (and, furthermore, not specifically documented as such) is disappointingly and confusingly inconsistent.

**Comment by tdmalone** [comment]
Yes it’s definitely inconsistent and needs to be fixed.

Regarding multi line though - try the syntax I mentioned with semicolons in the first post of this issue.

**Comment by beamerblvd** [comment]
Thanks for that suggestion, @tdmalone. It did help, though I couldn't use semicolons. Semicolons will let all commands execute, even if some commands fail. That can cause problems. The build should exit on the first failed command. But `&&` worked:

```yaml
- stage: deploy
  os: linux
  dist: xenial
  jdk: openjdk8
  deploy:
    - provider: script
      script:
        openssl aes-256-cbc ...... -in .travis.secrets.tar.enc -out .travis.secrets.tar -d &&
        tar -xvf .travis.secrets.tar &&
        rm .travis.secrets.tar &&
        gpg --import travis.gpg &&
        rm travis.gpg &&
        mv settings.xml $HOME/.m2/settings.xml &&
        mvn clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P sign -B -V -e
      on:
        tags: true
      skip_cleanup: true
    - provider: releases
      api_key:
        secure: CKKEi9hoNj......U80Q=
      file_glob: true
      file:
        - $HOME/.m2/repository/path/to/project-*.pom
        - $HOME/.m2/repository/path/to/project-*.pom.asc
        - $HOME/.m2/repository/path/to/project-*.pom.md5
        - $HOME/.m2/repository/path/to/project-*.pom.sha1
      on:
        tags: true
```

**Comment by andykais** [comment]
@beamerblvd thank you for the workaround, it almost works, except that I believe you are missing the `>-` character at the start of your multiline string.

I think this is relevant to the initial issue as well though. A similar issue can be seen when trying to use yaml's syntax for [block scalar styles](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210)

```yaml
- stage: deploy
  script: skip
  deploy:
    provider: script
    script: |
      echo first
      echo second
```
this will result in the output
```
firstnsecondn
```
where newlines are being interpreted as `n`.

Using proper yaml syntax, I would suggest the best way forward for deploy scripts is to use
```yaml
deploy:
  provider: script
  script: >-
    echo hello &&
    echo world
```
which ensures zero newlines are created. Of course, its still not as nice as allowing newlines, which offers the possibility to add comments to your scripts. Here is a working example I have on one of my repos https://travis-ci.com/andykais/scrape-pages/builds/102889342/config.
