### ISSUE TITLE
Unable to deploy different environments from master branch

### ISSUE THREAD

**Issue by rajkumaranuk** [travis-ci/dpl#693]
```yaml
deploy:
 - provider:                elasticbeanstalk
    script:       	         echo "Deploy master (SpringbootconfigAPI-dev)"
    on:
      branch:                master
      condition:             -z $TRAVIS_TAG
    app:                     "Springbootconfig API"
    bucket_path:             "Springbootconfig API"
    skip_cleanup:            true
    bucket_name:             "elasticbeanstalk-eu-west-1-829070902612"
    env:                     SpringbootconfigAPI-dev
    region:                  eu-west-1

  - provider:                elasticbeanstalk
    script:       	         echo "Deploy customer-dev (APICustomerConfigService-deva)"
    on:
      branch:                master
      condition:             -z $TRAVIS_TAG
    app:                     "APICustomerConfigService"
    bucket_path:             "APICustomerConfigService"
    skip_cleanup:            true
    bucket_name:             "elasticbeanstalk-eu-west-1-829070902612"
    env:                     APICustomerConfigService-deva
    region:                  eu-west-1
```

It fails with the following error when deploying from master branch into 3 beanstalk environments. (but works fine when deploying from different branches)

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/rubyzip-1.2.1/lib/zip/file.rb:396:in `check_entry_exists': add failed. Entry .ebextensions/30-elb.config already exists (Zip::EntryExistsError)
```
Please advice. Thanks for any help.

**Comment by BanzaiMan** [comment]
During the deployment, ElasticBeanstalk provider creates a ZIP file to upload. This file is not cleaned up, since we assume that the deployment happens exactly once. This is a problem if you try to deploy more than once.

Unfortunately, it is a bit involved to find the file name under all circumstances. However, something like this *_may_* work for you in your particular case:

```yaml
deploy:
  - provider: elasticbeanstalk
    ⋮ # rest
  - provider: elasticbeanstalk
    before_deploy:
      - find . -name \*.zip -print -delete
    ⋮ # rest
```
