### ISSUE TITLE
Allow APP_NAME in cloudfoundry

### ISSUE THREAD

**Issue by abdonrd** [travis-ci/dpl#699]
It would be great can set `APP_NAME` in the cloudfoundry provider.

Something like:

```yaml
deploy:
  - provider: cloudfoundry
    username: apikey
    password: $BLUEMIX_API_KEY
    api: https://api.ng.bluemix.net
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    manifest: manifest.yml
    app_name: $APP_NAME  # <= Set the app name
    skip_cleanup: true
    on:
      branch: master
```
