### ISSUE TITLE
Elasticbeanstalk: After deployment commands

### ISSUE THREAD

**Issue by BigChief45** [travis-ci/dpl#748]
I am looking for a way to collect the static files from my Django app after it is deployed to ElasticBeanstalk. Initially I was trying this in `.travis.yml`, as per [the docs](https://docs.travis-ci.com/user/deployment/elasticbeanstalk/):

```yaml
deploy:
  # ...
after_deploy:
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
```
However I think this is not correct, since this is probably still being executed in TravisCI and not in ElasticBeanstalk. 

What is the correct way to achieve this? I am aware that the EB CLI supports a `.ebextensions` that includes custom commands to be run as part of the deloyment. But I am not sure how to achieve a similar result with TravisCI.

Possibly related: #543
