### ISSUE TITLE
Using `edge` for a second provider results in LoadError

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/dpl#763]
# Problem

Given configuration such as

```yaml
deploy:
  - provider: script
    script: echo foo
    skip_cleanup: true
    on:
      all_branches: true
  - provider: script
    script: echo bar
    skip_cleanup: true
    github_token: foo
    edge: true
    on:
      all_branches: true
```

The second deployment results in `LoadError`:

```
Successfully installed dpl-script-1.9.1.travis.2669.5
1 gem installed
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- dpl/provider/script (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/provider.rb:92:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/provider.rb:67:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/provider.rb:66:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.1.travis.2669.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
```

See, for example:

https://travis-ci.org/BanzaiMan/travis_production_test/builds/348413224

# Workaround

Use the same version everywhere:

```yaml
deploy:
  - provider: script
    script: echo foo
    skip_cleanup: true
    edge: true # ← new!
    on:
      all_branches: true
  - provider: script
    script: echo bar
    skip_cleanup: true
    github_token: foo
    edge: true
    on:
      all_branches: true
```

https://travis-ci.org/BanzaiMan/travis_production_test/builds/348414697
