### ISSUE TITLE
Provider testing with local installation is currently broken

### ISSUE THREAD

**Issue by dazz** [travis-ci/dpl#770]
I tested a provider as described

https://github.com/dazz/dpl/commit/1e0aeaade8adbb9232a6714d0a625c20b348af33

```yml
deploy:
  provider: opsworks
    edge:
       source: dazz/dpl
       branch: opsworks-update-app-on-success
    access_key_id: abcdefg
    secret_access_key: ultrA-5ecr3t
    app-id: 11223344-5566-7788-9900-aabbccddeeff
    on:
      branch: master
    wait-until-deployed: true
    update-app-on-success: true
```

failing build: https://travis-ci.com/easybib/bib-cd/builds/67718282 (private repo)

Error:

```bash
Installing deploy dependencies
ERROR:  Could not find a valid gem 'dpl-ops_works' (= 1.9.0) in any repository
ERROR:  Possible alternatives: BibOpsworks, opsworks, opzworks, passworks
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- dpl/provider/ops_works (LoadError)
        from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:92:in `rescue in block in new'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:67:in `block in new'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:41:in `fold'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/provider.rb:66:in `new'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:31:in `run'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/lib/dpl/cli.rb:7:in `run'
        from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.0/bin/dpl:5:in `<top (required)>'
        from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
        from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

Thanks for your help!
