### ISSUE TITLE
Unable to deploy to forge.puppet.com

### ISSUE THREAD

**Issue by zerodecimal** [travis-ci/dpl#772]
Hello,

I am unable to deploy to the Puppet forge because of an unsatisfied dependency of dpl, json/pure. An example [job log is here](https://travis-ci.org/zerodecimal/zerodecimal-oracle_inventory/jobs/351511061) if you want to take a look. I did include json_pure in my Gemfile and can see that it did get installed. I'm a little confused because dpl is installing under a different ruby version (2.2.7) than I have specified in .travis.yml (2.4.1) for the build. I'm new at this and haven't got it to work yet, so let me know if I'm missing something.

**Comment by BanzaiMan** [comment]
Hello, there. Looks like we forgot to add `json_pure` to the run time dependencies for this provider. I pushed a potential fix. Please try it with:

```yaml
deploy:
  provider: puppetforge
  edge:
    branch: puppet_forge-post-1_9_0
  user: zerodecimal
  ⋮ # rest
```

and report the result? Thanks.

As for Ruby 2.2.7, it is the version that is pre-installed on the build image, and it is the one that we perform deployment with.
