### ISSUE TITLE
dpl 1.9.0: deploy to github pages fails

### ISSUE THREAD

**Issue by caarlos0** [travis-ci/dpl#777]
since dpl 1.9.0, my deploys to github pages are failing.

- [working deploy (dpl 1.8)](https://travis-ci.org/goreleaser/goreleaser/builds/350785724)
- [failing deploy (dpl 1.9)](https://travis-ci.org/goreleaser/goreleaser/builds/351004901)

error:

```
Couldn't push the build to github.com/goreleaser/goreleaser.github.io.git:master
failed to deploy
```

config:

```yaml
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: goreleaser/goreleaser.github.io
    local_dir: ./dist/goreleaser.github.io
    target_branch: master
    on:
      tags: true
      master: true
```
