### ISSUE TITLE
dpl 1.9.2 uploads S3 artefacts to incorrect path

### ISSUE THREAD

**Issue by sandfox** [travis-ci/dpl#786]
The following config 
```yml
      deploy:
        - provider: s3
          skip_cleanup: true
          upload-dir: main-branch-builds
          local_dir: artifact
```

under `dpl@1.9.1` uploads `my-file.tar.gz` from the `artifact` folder  to `/main-branch-builds/my-file.tar.gz`
```sh
uploading "my-file.tar.gz" with {:content_type=>"application/gzip"}
```

under `dpl@1.9.2` uploads `my-file.tar.gz`  from the `artifact` folder to `/main-branch-builds/artifact/my-file.tar.gz`
```sh
uploading "artifact/my-file.tar.gz" with {:content_type=>"application/gzip"}
```

The `1.9.1` behaviour was the expected for one for us

**Comment by BanzaiMan** [comment]
A potential fix is in the `releases-local_dir` branch.

Could you try this:

```yaml
deploy:
  - provider: s3
    edge:
      branch: releases-local_dir
    ⋮ # rest
```

and report the result? We'll have a 1.9.4 release shortly.
