### ISSUE TITLE
Timeout while uploading to GitHub Releases: Net::ReadTimeout (Faraday::TimeoutError)

### ISSUE THREAD

**Issue by cxbrooks** [travis-ci/dpl#796]
I'm uploading fairly large files to GitHub Releases using deploy and I'm seeing 

```
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Faraday::TimeoutError)
```
Any ideas?

Details below.

https://travis-ci.org/icyphy/ptII/jobs/359403072 failed during deploy.

The deploy part of my [.travis.yml](https://github.com/icyphy/ptII/blob/master/.travis.yml) looks like

```
env:
   # [Elided]
  global:
     # [Elided]
    - TRAVIS_TAG=nightly

#...

deploy:
  # [Elided]
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $PTII/doc/codeDoc*.jar
      - $PTII/adm/gen-11.0/capecode0.2.devel.setup.linux.tar.gz
      - $PTII/adm/gen-11.0/capecode0.2.devel.setup.mac.app.tar.gz
      - $PTII/adm/gen-11.0/capecode0_2_devel_setup_windows_64.exe
      - $PTII/adm/gen-11.0/ptII11.0.devel.setup.linux.tar.gz
      - $PTII/adm/gen-11.0/ptII11.0.devel.setup.mac.app.tar.gz
      - $PTII/adm/gen-11.0/ptII11_0_devel_setup_windows_64.exe
      - $PTII/adm/gen-11.0/ptII11_0_devel_setup_windows.exe
      - $PTII/adm/gen-11.0/ptII11.0.devel.src.tar
      - $PTII/adm/gen-11.0/ptII11.0.devel.src.zip
    on:
      tags: true
      condition: $PT_TRAVIS_INSTALLERS = true
    overwrite: true
    skip_cleanup: true
    verbose: true
```

The files that are to be uploaded are large (between 261Mb and 613Mb)

```
-rwxrwxr-x 1 travis travis  263470977 Mar 28 15:22 capecode0.2.devel.setup.linux.jar
-rw-rw-r-- 1 travis travis  452221788 Mar 28 15:21 capecode0.2.devel.setup.mac.app.tar.gz
-rwxrwxr-x 1 travis travis  391279040 Mar 28 15:16 capecode0_2_devel_setup_windows_64.exe
-rw-rw-r-- 1 travis travis  463312188 Mar 28 15:14 ptII11.0.devel.setup.linux.tar.gz
-rw-rw-r-- 1 travis travis  613702279 Mar 28 15:18 ptII11.0.devel.setup.mac.app.tar.gz
-rwxrwxr-x 1 travis travis  551971002 Mar 28 15:12 ptII11_0_devel_setup_windows_64.exe
-rwxrwxr-x 1 travis travis  540590804 Mar 28 15:10 ptII11_0_devel_setup_windows.exe
-rw-rw-r-- 1 travis travis  549898240 Mar 28 15:06 ptII11.0.devel.src.tar
-rw-rw-r-- 1 travis travis  261495314 Mar 28 15:07 ptII11.0.devel.src.zip
```

The failure from https://travis-ci.org/icyphy/ptII/jobs/359403072 is below:

```
Logged in as Christopher Brooks
Deploying to repo: icyphy/ptII
Current tag is: nightly
codeDocCapeCode.jar already exists, overwriting.
codeDocViptos.jar already exists, overwriting.
codeDocHyVisual.jar already exists, overwriting.
codeDocVisualSense.jar already exists, overwriting.
codeDocBcvtb.jar already exists, overwriting.
codeDoc.jar already exists, overwriting.
capecode0.2.devel.setup.linux.tar.gz already exists, overwriting.
capecode0.2.devel.setup.mac.app.tar.gz already exists, overwriting.
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Faraday::TimeoutError)
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:853:in `start'
     from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/net/http.rb:1375:in `request'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.5/lib/dpl/provider/releases.rb:138:in `upload_file'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.5/lib/dpl/provider/releases.rb:123:in `block in push_app'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.5/lib/dpl/provider/releases.rb:109:in `each'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-releases-1.9.5/lib/dpl/provider/releases.rb:109:in `push_app'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `block in deploy'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:41:in `fold'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/provider.rb:194:in `deploy'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:32:in `run'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/lib/dpl/cli.rb:7:in `run'
     from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.5/bin/dpl:5:in `<top (required)>'
     from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
     from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
dpl.3
Deploying application
failed to deploy
```

I saw a similar failure with another job [kepler-build #11](https://travis-ci.org/icyphy/kepler-build/builds/359099265)

I'm going to attempt to use  dpl from the command line to reproduce this, but I was wondering if anyone had any ideas?
