### ISSUE TITLE
Ruby on Rails - deploy flow to Heroku error

### ISSUE THREAD

**Issue by imadmoussa1** [travis-ci/dpl#801]
I am working on RUBY on Rails project with gitlab-ci and using the simple deploy flow to Heroku , when i push my code I have this error : 

> /usr/local/rbenv/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb:2291:in `raise_if_conflicts': Unable to activate dpl-heroku-1.9.1, because dpl-1.9.5 conflicts with dpl (= 1.9.1) (Gem::ConflictError)

this is the configuration of gitlab-ci :

```
deploy:
  type: deploy
  environment: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEV --api-key=$HEROKU_DEV_KEY
```
