### ISSUE TITLE
Elastic beanstalk provider doesn't support .ebextensions

### ISSUE THREAD

**Issue by leonardloo** [travis-ci/dpl#804]
When I run `eb deploy`, the config files in my `.ebextensions` folder are being loaded into the EB environment. I'm unable to do it with Travis-CI elasticbeanstalk provider. 

Is there a workaround for this? I tried creating an .ebextensions folder before_deploy but turns out this wasn't loaded into EB environment. Here's my .travis.yml:
```
sudo: required

services:
  - docker

language: node_js
node_js:
- '6'

before_install:
  - npm i -g npm@5.3.0

script:
  - git remote set-branches --add origin $PROD_BRANCH $STAGING_BRANCH
  - git fetch 

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin # Put AWS in path
  # Login to AWS ECR, credentials defined in $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY
  - $(aws ecr get-login --no-include-email --region ap-southeast-1) 
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - export TAG=`if [ "$TRAVIS_BRANCH" == "release" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - sed -i -e "s/@TAG/$TAG/g" Dockerrun.aws.json # Add TAG to Dockerrun
  - git rm -f --ignore-unmatch Dockerfile; # Remove Dockerfile so provider runs on Dockerrun
  - rm -f Dockerfile
  # Generate random env variables to inject into EB env
  - node -e 'require("./config/config").randomInEnv("./env-injected.json")'
  - mkdir .ebextensions
  - cp ./env-injected.json .ebextensions/
  - mv ./.ebextensions/env-injected.json ./.ebextensions/env.config

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "formsg-staging"
    env: "formsg-staging-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-652261905145"
    on:
      branch: $STAGING_BRANCH

  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "formsg-prod"
    env: "formsg-prod-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-652261905145"
    on:
      branch: $PROD_BRANCH
```
