### ISSUE TITLE
no response code-deploy with wait-until-deployed:true option

### ISSUE THREAD

**Issue by jho2n** [travis-ci/dpl#805]
HI, 

We are using code deploy dpl, since when, 
No response while deploying code deployment with wait-until-deployed option.
we deploy multiple instances with blue/green deployments. so always, travis throws error, and we can't catch if it is real error or timeout error.

travis error shown below
<img width="1217" alt="screen shot 2018-04-24 at 4 11 02 pm" src="https://user-images.githubusercontent.com/5358639/39171539-1ff56696-47da-11e8-9820-b78ab1302f99.png">

**Comment by BanzaiMan** [comment]
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by jho2n** [comment]
sorry for missing log 

this is my travis.yml
```yml
sudo: required
dist: trusty
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.21.0
branches:
  only:
    - release
    - dev
    - staging
    - /^deploy-.*$/
  except:
    - master
    - dontrunme
    - test
before_install:
  # install docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - echo $(docker --version)
  # install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo $(docker-compose --version)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker-compose -f docker/dev.docker-compose.yml run --rm api.dist
  - docker-compose -f docker/dev.docker-compose.yml down -v
  - docker logout
after_success:
  - ./after_success.sh
  - zip -r ${AWS_CODEDEPLOY_APPNAME}.zip dist/* aws_scripts/* appspec.yml
  - mkdir -p dpl_cd_upload
    && mv ${AWS_CODEDEPLOY_APPNAME}.zip dpl_cd_upload/${AWS_CODEDEPLOY_APPNAME}.zip
after_failure:
  - exit 1
deploy:
  - provider: s3
    region: $AWS_REGION
    bucket: $AWS_S3_BUCKET
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch:
        - staging
        - release
  - provider: codedeploy
    region: $AWS_REGION
    bucket: $AWS_S3_BUCKET
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: ${AWS_CODEDEPLOY_APPNAME}.zip
    bundle_type: zip
    application: $AWS_CODEDEPLOY_APPNAME
    deployment_group: $AWS_DEPLOYMENT_GROUP
    wait-until-deployed: true
    on:
      branch:
        - staging
  - provider: codedeploy
    travis_wait: 30
    region: $AWS_REGION
    bucket: $AWS_S3_BUCKET
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: ${AWS_CODEDEPLOY_APPNAME}.zip
    bundle_type: zip
    application: $AWS_CODEDEPLOY_APPNAME
    deployment_group: $AWS_DEPLOYMENT_GROUP_PROD
    wait-until-deployed: true
    on:
      branch:
        - release
```

and this is bulid log while deploying
```
travis_time:end:09ad3cc6:start=1524557857583311261,finish=1524557857696567324,duration=113256063
[0Ktravis_fold:end:after_success.2
[0Ktravis_fold:start:after_success.3
[0Ktravis_time:start:08c97c85
[0K$ mkdir -p dpl_cd_upload && mv ${AWS_CODEDEPLOY_APPNAME}.zip dpl_cd_upload/${AWS_CODEDEPLOY_APPNAME}.zip

travis_time:end:08c97c85:start=1524557857701999959,finish=1524557857749797315,duration=47797356
[0Ktravis_fold:end:after_success.3
[0Ktravis_fold:start:dpl_0
[0Ktravis_time:start:0b5c581e
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.5
1 gem installed

travis_time:end:0b5c581e:start=1524557862699040853,finish=1524557863998476362,duration=1299435509
[0Ktravis_fold:end:dpl_0
[0Ktravis_time:start:12f749b8
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Successfully installed jmespath-1.4.0
Successfully installed aws-sigv4-1.0.2
Successfully installed aws-sdk-core-2.11.36
Successfully installed aws-sdk-resources-2.11.36
Successfully installed aws-sdk-2.11.36
Successfully installed mime-types-2.99.3
Successfully installed dpl-s3-1.9.5
7 gems installed

travis_fold:end:dpl.1
Logging in with Access Key: ****************VFMQ
Beginning upload of 1 files with 5 threads.
travis_fold:start:dpl.2
[33mPreparing deploy[0m

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
uploading "s-api.zip" with {:content_type=>"application/zip"}

travis_fold:end:dpl.3

travis_time:end:12f749b8:start=1524557864006211152,finish=1524557871130365314,duration=7124154162
[0K[33;1mSkipping a deployment with the codedeploy provider because this branch is not permitted[0m
travis_fold:start:dpl_2
[0Ktravis_time:start:1854d3c4
[0K$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.9.5
1 gem installed

travis_time:end:1854d3c4:start=1524557872104529579,finish=1524557873396888831,duration=1292359252
[0Ktravis_fold:end:dpl_2
[0Ktravis_time:start:024aeb33
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
Successfully installed dpl-code_deploy-1.9.5
1 gem installed

travis_fold:end:dpl.1
Logging in with Access Key: ****************VFMQ
Registering app revision with version=GEsUgF4ZkihnWR6iTH2hexxmD4HN9rlG, etag="4dc7689db19e4700be0d15ac6568b6c9"
Triggered deployment "d-QAUOOZ03R".


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

As i know, prints dots every 5 seconds during deploying [by this function.](https://github.com/travis-ci/dpl/blob/ea585a280637bb3b6ddeac5b575632b9bfb60132/lib/dpl/provider/code_deploy.rb#L114)

but print only 1 dot after `Triggered deployment`
