### ISSUE TITLE
feature_request(gh_pages): track files before deploy

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/dpl#813]
### 1. Summary

It would be nice, if will be possible track files before deployment.

### 2. Argumentation

I use [**`filetime_from_git` plugin**](https://github.com/getpelican/pelican-plugins/tree/master/filetime_from_git), that automatically show first and last commit time for file. Part of `filetime_from_git` documentation:

> The date is determined via the following logic:

>  1. if a file is not tracked by Git, or a file is staged but never committed
>          + metadata['date'] = filesystem time
>          + metadata['modified'] = filesystem time

>  2. if a file is tracked, but no changes in staging area or working directory
>          + metadata['date'] = first commit time
>          + metadata['modified'] = last commit time

>  3. if a file is tracked, and has changes in stage area or working directory
>          + metadata['date'] = first commit time
>          + metadata['modified'] = filesystem time

**If** manual deploy:

    behavior as 3 item

**else** Travis CI deploy:

    behavior as 1 item. `filetime_from_git` show filesystem file. It is useless in practice.

### 3. Steps to reproduce

For build site manual and via Travis CI I use the same commands.

#### 3.1. Manual

I build my site manually on local machine → I move to folder with built site → I run in terminal:

```text
git add .
git commit -m "commit description"
git push
```

#### 3.2. Travis CI

I deploy site, use [**GitHub Pages Deployment**](https://docs.travis-ci.com/user/deployment/pages/).

Part of [**my `.travis.yml`**](https://github.com/Kristinita/KristinitaPelican/blob/master/.travis.yml) file:

```yaml
deploy:
  provider: pages
  on:
    branch: master
    condition: $GRUNT_COMMAND = publish
  keep-history: true
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/Kristinita.github.io
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  fqdn: Kristinita.ru
  project-name: Поиск Кристиниты
  verbose: true
```

### 4. Expected behavior

**If** manual deployment:

![Manual](https://i.imgur.com/YEqG1gM.png)

+ Posted — data of first commit
+ Last modified — data last page modified

### 5. Actual behavior

**Else** [**Travis CI deployment**](https://kristinita.ru/Programs/KristinitaLuckyLink):

![Travis](https://i.imgur.com/5raWLaI.png)

+ Posted — filesystem time
+ Last modified — filesystem time

Thanks.
