### ISSUE TITLE
using matrix in deploy section

### ISSUE THREAD

**Issue by LorneCurrie** [travis-ci/dpl#836]
Hi there

Is there a way we can deploy the same build artefact to say multiple S3 buckets (for example) that belong to the same AWS account and share some settings (region, local_dir, access_key, secret_access_key, and repo condition) using the matrix keyword?  Using the `travis encript` cli command, I ended up with the following config in my deploy section
```
deploy:
  matrix:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$BUILDS_BUCKET"
    region: "$REGION"
    skip_cleanup: true
    local_dir: dist/latest
    upload_dir: "$PROJECT/$ENVIRONMENT/$TRAVIS_BUILD_NUMBER"
    on:
      repo: our_repo-name
      branch:
      - develop
      - master
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$BUILDS_BUCKET_UAT"
    region: "$REGION"
    skip_cleanup: true
    local_dir: dist/latest
    upload_dir: "$PROJECT/$ENVIRONMENT/$TRAVIS_BUILD_NUMBER"
    on:
      repo: our_repo-name
      branch:
      - develop
      - master
  region:
    secure:
```
and then the region property is then shared between the 2 providers in the matrix object.  Would we be able to move all common setting to the deploy object and then the differences stay in the matrix object?

So the above would look like:
```
deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    matrix:
    - bucket: "$BUILDS_BUCKET"
    - bucket: "$BUILDS_BUCKET_UAT"
    region: "$REGION"
    skip_cleanup: true
    local_dir: dist/latest
    upload_dir: "$PROJECT/$ENVIRONMENT/$TRAVIS_BUILD_NUMBER"
    on:
      repo: our_repo-name
      branch:
      - develop
      - master
```

**Comment by joepvd** [comment]
Thanks for your suggestion! This is not directly supported as of yet.

You could use [YAML anchors](https://blog.daemonl.com/2016/02/yaml.html) if you want to avoid the duplication.

**Comment by webknjaz** [comment]
@LorneCurrie this is how to do this with YAML anchors:

```yaml
deploy:
  - &aws-deploy
    provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$BUILDS_BUCKET"
    region: "$REGION"
    skip_cleanup: true
    local_dir: dist/latest
    upload_dir: "$PROJECT/$ENVIRONMENT/$TRAVIS_BUILD_NUMBER"
    on:
      repo: our_repo-name
      branch:
      - develop
      - master
  - <<: *aws-deploy
    bucket: "$BUILDS_BUCKET_UAT"
```
