### ISSUE TITLE
Unable to deploy to Cloud Foundry with space name containing space characters.

### ISSUE THREAD

**Issue by rophy** [travis-ci/dpl#837]
This spec:

```yaml
deploy:
  provider: cloudfoundry
  username: rophy
  password: password
  organization: org123
  space: "my space with spaces"
```

Will fail with following error:

```
Preparing deploy
LICENSE
NOTICE
cf
Setting api endpoint to https://api.ng.bluemix.net...
OK

api endpoint:   https://api.ng.bluemix.net
api version:    2.75.0
Not logged in. Use 'cf login' to log in.
API endpoint: https://api.ng.bluemix.net
Authenticating...
OK

Targeted org org123


API endpoint:   https://api.w3ibm.bluemix.net (API version: 2.75.0)
User:           rophy
Org:            org123
Space:          No space targeted, use 'cf target -s SPACE'
FAILED
Error finding space my
Space my not found
```

Same result whether I put double quotes in space name or not in .travis.yml.

I think [cloud_foundry.rb#L12](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/cloud_foundry.rb#L12) is the problem. The command doesn't seem to be handling spaces.
