### ISSUE TITLE
deploy to chef supermarket requires newer version of ruby

### ISSUE THREAD

**Issue by majormoses** [travis-ci/dpl#841]
Per https://travis-ci.org/majormoses/tmpreaper/builds/405230423#L816-L832 we need a newer ruby version (>= 2.4) available. Any chance of exposing that as a configurable option so that in the future one can unblock self while waiting for the defaults to change?

**Comment by majormoses** [comment]
Looks like you can specify:
```
deploy:
  edge:
    branch: ruby-2.4
  provider: chef-supermarket
...
```

Trying that out.

**Comment by majormoses** [comment]
Actually it does not appear there is a branch for 2.4:
```
$ git checkout ruby-2.4
error: pathspec 'ruby-2.4' did not match any file(s) known to git.
```
Will try:
```
deploy:
  edge: true
  provider: chef-supermarket
...
```
