### ISSUE TITLE
byg(pypi): invalid option "--password=" if password doesn't contain special characters

### ISSUE THREAD

**Issue by Kristinita** [travis-ci/dpl#858]
### 1. Summary

I get the same error as in **#327**, but my PyPI password doesn't contain special characters.

### 2. Data

+ [**my PyPI profile**](https://pypi.org/user/Sasha_Chernykh/);
+ my password contain Latin letters (uppercase and lowercase) and numbers; no special characters;
+ [**SashaPypiDeploy branch**](https://github.com/Kristinita/SashaErichekCodeClimate/tree/SashaPypiDeploy) of my demo GitHub repository;

+ example `.travis.yml`:

```yaml
language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install --upgrade pip
script:
- python --version
deploy:
  provider: pypi
  user: Sasha_Chernykh
  password:
    secure: R2ZygTWCFqsxPBDWZ0YDkTysnFuKNQsc4m6GoQ2KGNOt8/iccMK9Z1hr7BN/qyUhS14L0udzwiC9B0V7hEDZm+ZaR9QSouETcsMhdIZkBDbdXbUUh+02R6VtnjEXYUc9fYdbSfcC9iA0ha5MPodQbnXipv450plgI7SQFttQMbbf6+F//Sz3t/eu2ij5Vfy1wPjuj5Z3cTLJvudQcA9LeoYHY0JkWUpin+wavC0Z0sbXorCIjbI4LDR04ef8CLH3IhMzrBZ9jJzl/ioMcC2FNbA6Fh6GX41BbZdTtOQl8BGkfnEuENgC6x0w0PD9gU59beLfGECDo34G5wniphxXJ+khHbkJW/OAycZYdj8nuaDRnq0EffK8OIzLHUiODsglg1kKSl5DUKjw4jN1WpI6nPEkiunivBzS2NLnZa+SLFHLWM04tUGe0Z1J1glfmtOFoi/0J+Pq0yiMNaliMpw2MgATzxSzOTniNoMajxmKb23jaM0awIuN/sAw4CXeP3aiMhI11XGtzGRWYER1jEV7tRDlgf0P82soQUeJ1h7FWXKyg8/qdZSqn7iAEZdhjxr7hf1ZJcBa0dELH3CMSr4mnEf46/7F7TDxCsXLpCp98XnhXhTSMIBFuKj1+kYzO/g+ANy3MQTCScLzbE2B3NJZ8vVSqzH7a68G2bOKu1MoWQk=
  on:
    branch: SashaPypiDeploy

```

```text
D:\SashaDemoRepositories\SashaErichekCodeClimate>travis lint
Hooray, .travis.yml looks valid
```

+ [**Build**](https://travis-ci.org/Kristinita/SashaErichekCodeClimate/builds/420702150#L451-L458):

```text
$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching: dpl-1.10.0.gem (100%)
Successfully installed dpl-1.10.0
1 gem installed
invalid option "--password="
failed to deploy
```

### 3. Steps to reproduce

I wrote in `.travis.yml`:

```yaml
password: myrealpassword
```

I [**print in terminal**](https://docs.travis-ci.com/user/deployment/pypi/):

```text
travis encrypt --add deploy.password
```

<kbd>Enter</kbd> → <kbd>Ctrl+Z</kbd> → <kbd>Enter</kbd> (as wrote in [**this comment**](https://github.com/travis-ci/travis-ci/issues/7327#issuecomment-379517192)). Secure will paste to my `.travis.yml` → I commit push my changes to GitHub.

#### 4.1. Manually password enter

I try as in [**this comment**](https://github.com/travis-ci/dpl/issues/327#issuecomment-137624430):

```
travis encrypt -r Kristinita/SashaErichekCodeClimate
```

I manually add password from terminal as value of `secure` key → I push changes to GitHub → [**no effect**](https://travis-ci.org/Kristinita/SashaErichekCodeClimate/builds/420696194).

#### 4.2. Already existing on PyPI package

I [**add my demo package to PyPI**](https://pypi.org/project/sashadebuggingpypideploy/) from local machine → I change version in `setup.cfg` → I push changes to GitHub → [**no effect**](https://travis-ci.org/Kristinita/SashaErichekCodeClimate/builds/420704861).

### 5. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Travis CLI 1.8.9

Thanks.
