### ISSUE TITLE
required support of `label` for `elasticbeanstalk` provider

### ISSUE THREAD

**Issue by jjuraszek** [travis-ci/dpl#859]
One of my builds output produce 2 separate application version. I have to name them with meaningful label. Right now it's impossible as only supported way to do it is with `ELASTIC_BEANSTALK_LABEL` which is global for all deployments. Desired format would be:

```
deploy:
  - provider: elasticbeanstalk
    label: first-label
     ...

  - provider: elasticbeanstalk
    label: second-label
     ...
```
