### ISSUE TITLE
Git says "not currently on any branch"

### ISSUE THREAD

**Issue by sigvaldm** [travis-ci/dpl#861]
Dear community, I've tried deployment to PyPI but all I get is:

```
Already up to date!
Not currently on any branch.
nothing to commit, working tree clean
Dropped refs/stash@{0} (749fb5512f16b14f6172ea302f5ba28037bfd9f0)
PyPI upload failed.
failed to deploy
```

I've added my password using "travis encrypt --add deploy.password" and "travis encrypt --pro --add deploy.password". I've tried both escaping special characters and not. I'm not even sure if authetication is the error, since the error message seems to suggest it's some Git thing, not an authentication thing. Any ideas?

**Comment by BanzaiMan** [comment]
If you are trying to upload a build artifacts on Travis CI, you'll need to add `skip_cleanup: true`. https://docs.travis-ci.com/user/deployment/pypi/#releasing-build-artifacts

**Comment by BanzaiMan** [comment]
Closing for now. If you still have issues after adding `skip_cleanup: true`, please respond with a build log URL that shows the problem.

**Comment by lewoudar** [comment]
Hello; I think I have the same issue as sigvaldm
Here is my [log](https://travis-ci.com/lewoudar/configuror/jobs/200202886)

And my deployment configuration is the following
```yaml
deploy:
  provider: pypi
  user: le_woudar
  password:
    secure: AGj+kiPyR8xeyxRKNbaAJzVUx1w1Aa+Piki8CiEWwTTWb6FDAzgngStNwdfvTlcIVb6fP+AK2rLDbhlj/u4cyNB+aR5ZnuM9XiI1drtYL4Y4D3jdbQlpoyh0lYG53P3OMyTOKoKB/RvKCtxisnHHIwvxn/Fok0obQoWT2XASqEmD9B3XSstkMLAjXfvDmMwfli8HJG1S+0FTEXY/BfFBdZzNMjbPiLTIaTTSfAtEO6YXdds9Bn64CyNAF1DExvN2rZzNA+xXbXj0ZqQFl3a+6Q9O+/YVCclJRplQP1ymQmIShHfD1j3Qz0xFOknPufz7zykJ7dTfIpe82NvGIBo47T8urNn3x/UZsdbELutgi9ljtQoyujPaTZsgu23Nu1pdwzOHRWoauLpGjO2zekX87BSY7EdC9FzGbWKy8g9tnOhg91eEuPCjoHTtSnyTB6kgozqDwNeSQTDGbZTpzabe0xG7O+v87RsOcIyBCHY2pfygr89RUWSsXNQGFDiw5fLiC/fdRyuGXrMPSFwNzDLMpVIbMGkvTNIHGBY9zJKRNYV5yOML2vI9hIUtu4i43rxbtIdWRkXHTOnsg4nWVJ7bntUpHFu5d4m1RwmatvyxHn7tbch928jc9kJ54pWokSIzwXWzr7x+8gZIQW49jXWNc7wA/F5h0gjE7oZRP2CRZ34=
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
````
