### ISSUE TITLE
New Provider: Docker Registry

### ISSUE THREAD

**Issue by poulad** [travis-ci/dpl#867]
### Feature :whale: 
A new provider to push docker images(build artifact) to a Docker registry such as hub.docker.com.
Multiple images can be published to different registries with Docker Hub being the default registry.

Here is what I have in mind as options:
```yml
deploy:
  docker:
    - source: local-foo
      target: foo/bar:edge
      registry: hub.docker.com # default
      user: foo
      password:
        - secure: ...
    - source: local-foo:latest
      target: bar/web:edge
      registry: registry.heroku.com
      user: foo
      password:
        - secure: ...
```

This should be easy to implement and in fact, I have already done so in JS. I have no experience with Ruby and cannot add it quickly myself.

Here is the script I use:

<https://github.com/Zevere/WebAPI-Borzoo/blob/110ba3d81af3468678dd52abd815d9b79700d32d/ci/deploy/deploy_docker_registry.js#L9-L12>

and the options (JSON) passed to it:
<https://github.com/Zevere/WebAPI-Borzoo/blob/110ba3d81af3468678dd52abd815d9b79700d32d/.travis.yml#L41>
