### ISSUE TITLE
feature request: distinguish github releases & pre releases

### ISSUE THREAD

**Issue by andykais** [travis-ci/dpl#904]
I have this workflow for npm publishing:
create github release, trigger travis deploy provider npm

Github has an option to label pre-releases. I like this idea because it lets me do all my package versioning (including beta package versioning) from within github. That is why I would like the ability to distiguish prereleases from regular releases within travis. That way, I can tag a npm "beta" release like this: `npm publish --tag next`

I see two possible solutions:
- travis includes a prerelease conditional in the travis.yml config
- set an environment variable like `GITHUB_PRERELEASE=<bool>`

[github release events](https://developer.github.com/v3/repos/releases/#get-a-single-release)  include a `prerelease` boolean, assuming travis is using webhooks this information is already available.

**Comment by BanzaiMan** [comment]
I did not mention previously that you can pass `prerelease: true` for this purpose. You'll have to set up different deployment providers (or different stages), but this is already possible.

I also suggest using YAML anchors to reduce duplication.

```yaml
release_def: &release
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release.tar.gz
  on:
    tags: true
deploy:
  - *release
  - <<: *release
    prerelease: true
```
