### ISSUE TITLE
Creating draft GitHub releases breaks tag tying

### ISSUE THREAD

**Issue by PhrozenByte** [travis-ci/dpl#914]
As soon as I add `deploy.draft: true` to my `.travis.yml`, Travis no longer sets the release's tag to the tag that triggered the Travis build.

This config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  on:
    tags: true
```

results in

![bildschirmfoto von 2018-04-07 23-15-05](https://user-images.githubusercontent.com/920356/38460436-fbc5dfbc-3ab9-11e8-879b-ca7a63e07976.png)

whereas this config

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  draft: true
  on:
    tags: true
```

results in

![bildschirmfoto von 2018-04-07 23-29-06](https://user-images.githubusercontent.com/920356/38460511-85b342b8-3abb-11e8-8516-09fb8aace085.png)

The reason why it says "Existing tag" is not because this tag actually exists (the tag that triggered this Travis build is `v2.0.0-beta.3`), but because GitHub silently and unsolicitedly creates this tag as soon as you hit "Publish"... :unamused: 

It seems like Travis (or GitHub) looses the link between tag and release for some reason when creating a release draft.

This issue can be fixed by explicitly adding the `tag_name` and `target_commitish` variables (see https://github.com/picocms/Pico/commit/6d6a39b74441d68ae33c05dd610ca94d2e4d9b76):

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  draft: true
  on:
    tags: true
```

Both variables aren't documented in https://docs.travis-ci.com/user/deployment/releases/

However, I guess it's rather a bug that Travis (or GitHub) doesn't create the release draft using the tag that triggered the Travis build.

Follow-up to #8248

**Comment by pblitz** [comment]
We have the same issue - would love to have a draft release on every master merge...

**Comment by BanzaiMan** [comment]
Hello, everyone, sorry for the delay. I found some time to look at this in more detail, and I have a couple of questions.

First, does anyone have a build log URL that shows the problem?

Second, @PhrozenByte showed this configuration:

```yaml
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  draft: true
  on:
    tags: true
```

to report the problem, but this configuration by itself should not trigger a deployment on a tagged build. So I must be missing something.

[This build](https://travis-ci.org/BanzaiMan/travis_production_test/builds/455236475), triggered by [this configuration](https://github.com/BanzaiMan/travis_production_test/blob/f8bee77131ada697e274ca01ad4e51a3963de6dc/.travis.yml#L49-L56):

```yaml
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: test.rb
  draft: true
  on:
    all_branches: true
    tags: true
```

created a draft release correctly.

![releases_ _banzaiman_travis_production_test](https://user-images.githubusercontent.com/25666/48517966-0b48d280-e836-11e8-90f6-a8070773e64e.png)

**Comment by BanzaiMan** [comment]
Please test:

```yaml
deploy:
  provider: releases
  edge:
    branch: releases-improvements
  ⋮ # rest
```
Here, "rest" means whatever you use the Releases deployment provider for, including, but not limited to, `draft: true`, `on` conditions, etc. In particular, `draft: true` should result in a usable draft release, which should look like this:

![edit_release_ _banzaiman_travis_production_test](https://user-images.githubusercontent.com/25666/48525106-cda57300-e850-11e8-8f03-a89a13c4f0a8.png)

This was created by [this build](https://travis-ci.org/BanzaiMan/travis_production_test/builds/455295229).
