### ISSUE TITLE
Heroku build results is now 410 gone

### ISSUE THREAD

**Issue by simmerz** [travis-ci/dpl#918]
dpl doesn't return a exit code any more because the build result on heroku's platform API no longer exists: https://devcenter.heroku.com/articles/platform-api-reference#build-result

https://devcenter.heroku.com/articles/api-compatibility-policy#deprecation explains their deprecation policy.

This means it hangs in CI/CD environments

**Comment by cotsog** [comment]
@simmerz this should be fixed by https://github.com/travis-ci/dpl/pull/917.

Do you think you could help us validate the fix by running a build with the following in your .travis.yml file?

```yaml
deploy:
  provider: heroku
  edge:
    source: dmathieu/dpl
    branch: heroku-result
  ⋮
```

Thanks in advance!
