### ISSUE TITLE
Aws::ElasticBeanstalk::Errors::InvalidParameterValue

### ISSUE THREAD

**Issue by rutvikpensionwar** [travis-ci/dpl#954]
I am trying to set up automatic deployment Travis - AWS Elastic Beanstalk.

This is how my `.travis.yml` file looks like
```
sudo: required
services:
  - docker

before_install:
  - docker build -t rutvikpensionwar/docker-react -f Dockerfile.dev .

script:
  - docker run rutvikpensionwar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-271678594677"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
```

<img width="1023" alt="screen shot 2019-02-12 at 4 13 36 pm" src="https://user-images.githubusercontent.com/18364112/52677098-5af47400-2ee1-11e9-855c-86599947b60d.png">

I do have an AWS Elastic Beanstalk app named `docker-react`. Any help is appeciated.
