### ISSUE TITLE
elasticbeanstalk deployment failing: bucket_name.exists?

### ISSUE THREAD

**Issue by tmaximini** [travis-ci/dpl#956]
I am trying to deploy to elastic beanstalk from Travis as described here: https://docs.travis-ci.com/user/deployment/elasticbeanstalk/.

Here is my `.travis.yml`

```
language: node_js
node_js:
  - '10'
services:
  - docker
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id:
    secure:  __secure_id__
secret_access_key:
    secure: __secure_key__
  region: eu-central-1
  app: node-typescript-test
  env: e-xyz
  bucket_name: elasticbeanstalk-eu-central-1-xxxx
  on:
    branch: master
```

And here is the error logged from Travis:
 ```
Deploying application
S3 client configured for "eu-central-1" but the bucket "elasticbeanstalk-eu-central-1-xxxx" is in "eu-central-1"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts
Already up to date!
HEAD detached at 7154e08
nothing to commit, working tree clean
Dropped refs/stash@{0} (4685c24c8f6ef8bd44d83d0b5f087b44a8510633)
/home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-resources-2.11.222/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?': Aws::S3::Errors::BadRequest
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/aws-sdk-resources-2.11.222/lib/aws-sdk-resources/resource.rb:131:in `exists?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-elastic_beanstalk-1.10.8.travis.3178.5/lib/dpl/provider/elastic_beanstalk.rb:101:in `bucket_exists?'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-elastic_beanstalk-1.10.8.travis.3178.5/lib/dpl/provider/elastic_beanstalk.rb:41:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8.travis.3178.5/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

The bucket `elasticbeanstalk-eu-central-1-xxxx` exists in my S3. Manual deploy using the `eb` CLI tools worked. 
I have no idea what to make from this error. 
PS: The IAM role i created has `AmazonS3FullAccess` and `AWSElasticBeanstalkFullAccess` permissions.

**Comment by tmaximini** [comment]
it seems that I used a wrong format for my `access_key_id` and `access_key_secret`.
Now I used the following format in `.travis.yml` and it works.

```
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id: $ACCESSKEYID
  secret_access_key: $ACCESSKEYSECRET
  region: eu-central-1
  app: node-typescript-test
  env: node-typescript-test-dev
  bucket_name: elasticbeanstalk-eu-central-1-xxxx
  on:
    branch: master
env:
  global:
    - secure: 
LNmnzf35i5YSRMTy8rJ51KUPd1SwQvblm0nJ2sXunNDm/2n+GbRQQ/y1ghvY+UEBLkJ/qapVaEk/32/bpgnhA7h/WgMRTu1FNCAGo4fTROZYhvyRIg0FwP2KKmL0FzDmqEnK/xPaYGMob2CC6szJ4GFzaifgcU8n/Zx0l0BhDl1nWbBrLM4Xslzw5K0kl8/HEnNzwSa4869gibKniRvgdOZ9LpNRdcKCtr1eSAV5KbFV0r/BSt+zAw+oZmrRQgL4rwiDE3QQMV6rHrVsG/FsGxCsrXq8/SNBTX34NDNfXEqylzYXYf5wWkAry0+uUmL1Q81i3+277MRQmca+ypivfxQ06e2+xYDDteje2DUyXZEhfxC/hJT/tx/+RQayz4fRNHeDR0GACvCZSEehxnM/GkQvrqFAfr5QVnlorj5pEVnd6xFbtiGahvmuctC5WAe/LHrZ892saBqYXld8UuP8ILff/MWE478MlRJJxKL8A3LxjTlQJi4Q5X4Mpt0weAANXp3iDImziPthKSQdwznbsgoF5AN9ix9Q6zz1eLl4/CXmhW/6NGVMtNnU3/MAToK1D6wEdQnPiQ267B1n+HiULTZrqAEpOuwjBSNE817kB+PdLpjjNXpb2T41I9Au3S0fi5TAIAt7qEcLBIUeOrrs8O+sadasddasda+PzVUURI=
    - secure: chn8hjw2AK5bhSOtlYMRypAIuxhIfHeVLHTP/Qm4jqZCIGZOCGqOwb6qICNlZDUFiedCXSB9ein90i+e1SR/gCjHw3OZUfVRohc8BLoW9VmoIZUzzPCnWpWGfYi5T3L4TVDjXJAWBc05GLn7R0s8de+BPkYS3PjApt0gf8TippkVVIMHVrtJ0DronTUi4Vlfn3WZZaHAO5fRNz03Cl7q8EJyXEV3qV0QJ8V3pz47CQiZUyLRZNiDlSOw9dnm9bJn+4GkBiS3J+IibjyIo4x+asdasdasda/w33neDgVe3pK/+S2JZg2BQsk84n4JDTMe15P2geCAJlcAImtHlJdqUGFKrHsYNXlh2+owGizmBGGKVVKLvXBRysS02FFtpJTNTWAkLiTkEpSEknOAjGHS6ja9gfqeMHBHFz/D7ogvi3DrZRm8t2Dtt2c1ocEjMN/rL5cJeh8JVq7Z1PNe+GwiyPnvw9korx6C0iiluGye5maLDO/GN2V7t8cb1QXSSMYNTuJSPn9RYuycNxc7mxtX53Knz7xnIs9d8ezTpTgh0KWC+zLlReYSeC7y1EfmKLE7ukHwf91rgO1cNx1D4fU0rI9FFv8GP3D0TZnAt1CuNGW7YzghlgcSUUalhJyYyVv9oBOQcMJf2Te6gCb1x6s97fVVISrUZQPo62/qpZO0=
```
