### ISSUE TITLE
couldn't get build folder into deploy zip file : EB Provider

### ISSUE THREAD

**Issue by abhishek-mittal** [travis-ci/dpl#979]
```
image: node:latest

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get install -y unzip fontconfig locales gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget ruby-dev
  - npm install --silent

stages:
  - build
  - production

release:build:
  stage: build
  script: 
    - node_modules/.bin/ng build --prod --aot
    - ls
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - master

aws:prod:
  type: deploy
  stage: production
  image: ruby:latest
  dependencies:
    - release:build
  before_script:
    - gem install dpl
  script:
    - rm -r node_modules
    - ls
    - dpl --provider=elasticbeanstalk --access-key-id=$AWS_ACCESS_KEY_ID --secret-access-key=$AWS_SECRET_ACCESS_KEY --app=$AWS_APP --env=$AWS_APP_ENV --region=$AWS_REGION --bucket-name=$AWS_BUCKET_NAME --skip-cleanup
    - ls
  only:
    - master
```
my gitlab-ci.yml file
dpl --skip_cleanup not working each time the deploy file is being created without the dist folder or any other file I want to add to the final file before deployment.
Please help with this issue.
