### ISSUE TITLE
syswrite': Broken pipe (Faraday::ConnectionFailed)

### ISSUE THREAD

**Issue by kenorb** [travis-ci/dpl#981]
I've the same error, despite restarting build 5 times.

Build: [513638654](https://travis-ci.org/EA31337/EA31337/jobs/513638654), also with another tag [513636620](https://travis-ci.org/EA31337/EA31337/jobs/513636620)

```
Deploying to repo: EA31337/EA31337
Current tag is: beta
/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `syswrite': Broken pipe (Faraday::ConnectionFailed)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `do_write'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:343:in `write'
...
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.8/lib/dpl/provider/releases.rb:163:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.8/lib/dpl/provider/releases.rb:136:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.8/lib/dpl/provider/releases.rb:119:in `each'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.8/lib/dpl/provider/releases.rb:119:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
```

Related:
- GH-229 & GH-816

----

`.travis.yml` deploy section:
```
deploy:
  provider: releases
  api_key:
  - secure: MYSECRET
  file:
    - "*.ex4"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: EA31337/EA31337
    condition: "$DEPLOY = 1"
    tags: true
after_deploy:
- make clean
```
