### ISSUE TITLE
Only Deploy When Commit/Tag is Signed

### ISSUE THREAD

**Issue by nikeee** [travis-ci/dpl#988]
Is there an option to require a PGP signature on the commit or tag (by a specific key)?

Something like this:
```yaml
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true
  on:
    branch: release
    signed_by: 0xDEADBEEF
```
