### ISSUE TITLE
pypi deployment dependencies installation fails

### ISSUE THREAD

**Issue by paulfariello** [travis-ci/dpl#993]
Using a pypi deployment I get the following error:
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:97:in `rescue in block in new': uninitialized constant DPL::Provider::Pipy (NameError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

My configuration is:
```
language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install nose
script: nosetests
deploy:
  provider: pipy
  user: <redacted>
  password:
    secure: <redacted>
  on:
    tags: true
    python: "3.6"
  skip_existing: true
```
